<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Introduction to Survival Analysis - Smart Analytics for Big Data</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
		<meta property="og:title" content="Introduction to Survival Analysis" />
<meta property="og:description" content="A FINIR
Exercise - Unemployment durationSurvival analysis models covariates that influence time-to-event.
OLS regression methods are less efficient because the time-to-event is typically not normally distributed (positive, skewed, nearly discret when rounding are present), and the model cannot handle censored observation, without modification.
library(Ecdat)## Warning: le package &#39;Ecdat&#39; a été compilé avec la version R 3.6.3## Le chargement a nécessité le package : Ecfun## Warning: le package &#39;Ecfun&#39; a été compilé avec la version R 3." />
<meta property="og:type" content="article" />
<meta property="og:url" content="/lessons_list/lesson_3-2_survanalyse-application/" />


	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">
	<link rel="stylesheet" href="/css/style.css">
	
	<link rel="shortcut icon" href="/favicon.ico">
		
</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="Smart Analytics for Big Data" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">Smart Analytics for Big Data</div>
					<div class="logo__tagline">Lesson at Grenoble Inp - IEM</div>
				</div>
		</a>
	</div>
		
<nav class="menu">
	<button class="menu__btn" aria-haspopup="true" aria-expanded="false" tabindex="0">
		<span class="menu__btn-title" tabindex="-1">Menu</span>
	</button>
	<ul class="menu__list">
		<li class="menu__item">
			<a class="menu__link" href="/lessons_list/">
				
				<span class="menu__text">Lessons</span>
				
			</a>
		</li>
		<li class="menu__item">
			<a class="menu__link" href="/prerequisites/">
				
				<span class="menu__text">PreRequisites</span>
				
			</a>
		</li>
		<li class="menu__item">
			<a class="menu__link" href="/otherlessons/">
				
				<span class="menu__text">Other Lessons</span>
				
			</a>
		</li>
		<li class="menu__item">
			<a class="menu__link" href="/about/">
				
				<span class="menu__text">About</span>
				
			</a>
		</li>
	</ul>
</nav>

	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">Introduction to Survival Analysis</h1>
			<div class="post__meta meta"><div class="meta__item-categories meta__item"><svg class="meta__icon icon icon-category" width="16" height="16" viewBox="0 0 16 16"><path d="m7 2l1 2h8v11h-16v-13z"/></svg><span class="meta__text"><a class="meta__link" href="/categories/r/" rel="category">R</a>
	</span>
</div></div>
		</header><div class="content post__content clearfix">
			


<p><strong>A FINIR</strong></p>
<div id="exercise---unemployment-duration" class="section level1">
<h1>Exercise - Unemployment duration</h1>
<p>Survival analysis models covariates that influence time-to-event.</p>
<p>OLS regression methods are less efficient because the time-to-event is typically not normally distributed (positive, skewed, nearly discret when rounding are present), and the model cannot handle censored observation, without modification.</p>
<pre class="r"><code>library(Ecdat)</code></pre>
<pre><code>## Warning: le package &#39;Ecdat&#39; a été compilé avec la version R 3.6.3</code></pre>
<pre><code>## Le chargement a nécessité le package : Ecfun</code></pre>
<pre><code>## Warning: le package &#39;Ecfun&#39; a été compilé avec la version R 3.6.3</code></pre>
<pre><code>## 
## Attachement du package : &#39;Ecfun&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:base&#39;:
## 
##     sign</code></pre>
<pre><code>## 
## Attachement du package : &#39;Ecdat&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:datasets&#39;:
## 
##     Orange</code></pre>
<pre class="r"><code>data(Unemployment)
Unemployment # Necessary to obtain the DF !</code></pre>
<pre><code>##     duration spell     race    sex reason search pubemp ftp1 ftp2 ftp3 ftp4
## 1          4     1    white   male reentr    yes    yes    1    0    0    0
## 2          7     0    white   male   lose     no     no    1    1    1    1
## 3          1     0 nonwhite   male   lose     no     no    0    0    0    0
## 4          1     1 nonwhite   male reentr     no     no    0    1    0    0
## 5          3     1 nonwhite female reentr     no     no    0    0    0    0
## 6          1     1    white female reentr     no     no    0    0    0    0
## 7         65     0    white   male   lose    yes    yes    1    1    1    1
## 8          4     0    white female reentr     no     no    0    0    0    0
## 9        113     0    white female reentr     no     no    0    0    0    0
## 10         9     1    white   male  leave    yes     no    1    0    0    1
## 11         9     1    white   male  leave    yes     no    1    1    0    0
## 12       104     0    white   male  leave    yes     no    1    0    0    1
## 13        21     0    white female reentr     no    yes    1    1    1    1
## 14        20     0    white female   lose     no     no    1    1    1    1
## 15         8     1    white   male reentr     no     no    1    0    0    0
## 16       104     1    white female   lose    yes     no    1    0    1    0
## 17        20     1    white   male   lose     no     no    1    1    0    0
## 18        56     1 nonwhite female reentr     no     no    0    0    0    0
## 19        61     0    white female   lose     no    yes    1    1    1    1
## 20         3     0    white female  leave     no     no    1    0    0    1
## 21         2     0    white female reentr    yes     no    1    0    0    1
## 22         1     1    white female   lose     no     no    0    0    0    0
## 23        22     1    white female  leave     no    yes    1    1    1    0
## 24        12     1 nonwhite   male reentr     no     no    0    1    0    0
## 25         7     1 nonwhite female reentr     no     no    0    0    0    0
## 26       104     1 nonwhite   male reentr    yes    yes    0    1    0    0
## 27        12     0    white female    new     no     no    0    0    0    0
## 28        17     0    white female   lose    yes     no    1    1    1    1
## 29        17     0    white   male reentr     no     no    1    0    0    0
## 30         1     1    white   male reentr     no     no    0    0    0    0
## 31        12     1    white   male   lose     no     no    1    1    1    0
## 32        10     0    white   male   lose     no     no    1    1    1    1
## 33         1     0    white   male  leave     no     no    1    0    0    1
## 34        10     1 nonwhite female   lose     no    yes    1    1    1    0
## 35       108     1    white   male   lose     no     no    1    1    0    1
## 36       104     1    white female   lose    yes     no    0    1    0    0
## 37        11     0 nonwhite female    new     no     no    0    0    0    0
## 38        56     1    white female  leave    yes     no    1    1    0    0
## 39        65     0    white   male reentr     no     no    1    1    1    1
## 40         7     1    white   male reentr     no    yes    1    0    1    0
## 41        35     1 nonwhite female   lose     no     no    0    0    0    0
## 42        61     0    white female   lose     no     no    1    1    1    1
## 43        56     1 nonwhite female  leave     no     no    1    1    0    0
## 44         3     1 nonwhite   male reentr    yes     no    0    0    0    0
## 45        35     0 nonwhite   male  leave     no     no    1    1    1    1
## 46        13     1    white female  leave    yes     no    1    0    0    0
## 47         2     1 nonwhite female   lose    yes     no    0    1    0    0
## 48         9     0    white female   lose     no     no    1    1    1    1
## 49         6     0    white   male    new     no     no    0    0    0    0
## 50         3     0    white female   lose     no     no    1    0    0    1
## 51       104     1    white   male reentr    yes    yes    1    0    0    0
## 52        16     0 nonwhite female   lose    yes     no    1    0    0    0
## 53         1     1    white female    new     no     no    0    0    0    0
## 54         7     0    white female    new    yes    yes    1    0    1    0
## 55        65     0    white   male reentr     no    yes    1    1    1    1
## 56         9     1    white female reentr     no     no    0    0    0    0
## 57         2     1    white female  leave    yes     no    1    0    0    0
## 58         5     0    white   male   lose     no     no    1    0    0    1
## 59         2     1    white female  leave    yes    yes    0    0    0    0
## 60         2     1    white female   lose     no     no    0    1    0    0
## 61         8     1    white female   lose     no    yes    1    1    0    0
## 62         7     1    white   male reentr     no     no    0    0    0    0
## 63         1     1    white   male reentr     no     no    1    0    0    0
## 64        13     0    white female   lose     no     no    1    1    1    1
## 65        12     0    white female   lose    yes     no    1    1    1    1
## 66         8     0    white   male   lose    yes     no    1    1    1    1
## 67        61     0    white female reentr    yes     no    0    0    0    0
## 68        17     0    white female reentr     no     no    0    0    0    0
## 69        26     0 nonwhite female    new     no     no    1    1    1    1
## 70        16     1 nonwhite female reentr     no     no    1    0    0    0
## 71         2     1 nonwhite female reentr     no     no    1    0    0    0
## 72         5     0 nonwhite female reentr     no     no    1    0    0    1
## 73         3     0 nonwhite female reentr     no     no    0    0    0    0
## 74        16     1    white female reentr     no     no    1    0    0    0
## 75        26     0    white female reentr    yes     no    1    0    1    0
## 76         4     0    white   male   lose    yes     no    1    0    0    1
## 77        13     1    white female    new     no     no    1    0    0    0
## 78        58     0    white   male   lose     no     no    1    1    1    0
## 79        14     1    white   male   lose    yes     no    1    0    0    0
## 80         1     0    white female   lose     no     no    1    0    0    1
## 81        15     0    white   male   lose     no     no    1    1    1    1
## 82         1     0    white female reentr     no     no    1    0    0    1
## 83         7     0    white   male  leave     no     no    1    1    1    1
## 84        10     1    white   male   lose    yes    yes    0    1    1    0
## 85        18     1    white female reentr     no     no    1    1    0    0
## 86        48     0    white   male   lose     no    yes    1    1    1    1
## 87        21     1    white   male   lose     no     no    0    1    0    0
## 88        12     0    white   male reentr     no     no    1    1    1    1
## 89         3     1    white female   lose     no     no    0    0    0    0
## 90        56     0    white   male  leave     no     no    1    1    1    1
## 91        15     0    white female reentr     no    yes    1    1    1    1
## 92         3     0    white   male   lose     no     no    1    0    0    1
## 93         2     1    white female reentr     no     no    0    1    0    0
## 94         3     1    white   male   lose     no     no    1    0    0    0
## 95        12     0    white female    new     no     no    0    0    0    0
## 96         1     1    white   male   lose     no     no    0    0    0    0
## 97         3     1    white   male   lose    yes     no    1    0    0    0
## 98         5     1    white   male   lose     no    yes    1    1    1    0
## 99         2     1    white female   lose    yes    yes    1    0    1    0
## 100        8     0    white   male  leave     no     no    0    0    0    0
## 101        9     0    white   male reentr     no     no    1    1    1    1
## 102       26     1    white female reentr    yes     no    0    0    0    0
## 103        1     0    white   male   lose     no     no    1    0    0    0
## 104        7     1    white female reentr     no     no    1    1    1    0
## 105        6     1    white female    new     no     no    0    0    0    0
## 106        5     1    white   male reentr     no     no    1    0    1    0
## 107        4     1 nonwhite female   lose    yes     no    1    0    0    0
## 108        9     0 nonwhite   male reentr     no    yes    0    0    0    0
## 109        5     1 nonwhite   male    new     no     no    0    0    0    0
## 110       12     1    white female reentr     no     no    1    1    1    0
## 111        4     0    white female reentr    yes     no    1    0    0    0
## 112       65     0 nonwhite female  leave     no     no    1    1    1    1
## 113        8     1 nonwhite female reentr     no    yes    1    1    0    0
## 114        8     1 nonwhite female    new     no     no    1    1    0    0
## 115       22     1 nonwhite female reentr     no     no    0    0    0    0
## 116       19     0 nonwhite female    new     no     no    1    1    1    1
## 117       38     1 nonwhite   male  leave     no     no    1    1    1    0
## 118       25     0 nonwhite   male   lose     no    yes    1    1    1    1
## 119       12     0 nonwhite female reentr    yes     no    1    0    1    1
## 120       26     1 nonwhite   male   lose    yes     no    1    0    0    0
## 121        2     1    white   male reentr    yes     no    0    0    0    0
## 122        8     1 nonwhite female   lose     no     no    0    0    0    0
## 123        6     1 nonwhite female    new     no     no    0    0    0    1
## 124        2     0    white   male reentr     no     no    0    0    0    0
## 125        1     1    white   male reentr     no     no    0    1    0    0
## 126        1     0    white   male  leave     no     no    1    0    0    1
## 127        3     1    white   male reentr     no     no    0    0    0    0
## 128       52     1    white   male  leave    yes     no    1    0    0    0
## 129        1     1    white   male   lose     no     no    0    0    0    0
## 130        1     0    white   male   lose     no     no    1    0    0    1
## 131        2     0    white   male reentr    yes     no    0    1    0    0
## 132        1     1    white female   lose     no     no    0    0    0    0
## 133        2     1    white female   lose     no     no    0    0    0    0
## 134       20     1    white female reentr     no    yes    1    1    1    0
## 135       35     1    white   male reentr     no     no    0    0    0    0
## 136       16     1    white female reentr    yes    yes    1    0    1    1
## 137       22     0    white   male  leave    yes    yes    1    0    0    0
## 138        1     0    white female reentr    yes     no    1    0    1    0
## 139       12     0 nonwhite female reentr     no    yes    1    1    0    0
## 140       11     0 nonwhite   male  leave     no    yes    1    1    1    1
## 141       12     0 nonwhite   male  leave     no    yes    1    1    1    1
## 142        7     1 nonwhite   male  leave    yes    yes    1    0    1    0
## 143       21     1    white   male   lose     no     no    0    1    0    0
## 144       27     0    white   male  leave    yes     no    1    1    1    1
## 145       23     0    white   male reentr    yes     no    1    1    1    1
## 146        3     1    white female   lose     no     no    0    0    0    0
## 147       22     1 nonwhite   male    new    yes     no    0    1    0    0
## 148        4     1    white female  leave     no     no    1    0    1    0
## 149       39     1    white   male   lose    yes     no    1    0    0    0
## 150       26     0    white female   lose     no     no    0    0    0    0
## 151       19     0    white female    new     no     no    0    0    0    0
## 152       16     1 nonwhite   male    new     no     no    0    0    0    0
## 153       11     0    white female reentr    yes     no    1    1    1    1
## 154       17     0    white   male  leave     no    yes    1    1    1    1
## 155       10     0    white female   lose     no     no    0    0    0    0
## 156        8     0    white female    new     no     no    0    0    0    0
## 157       25     0 nonwhite female   lose    yes    yes    1    1    1    1
## 158       48     0    white   male  leave     no     no    1    1    1    1
## 159        2     1    white   male  leave    yes     no    0    1    0    0
## 160       21     0    white   male   lose    yes    yes    1    1    1    1
## 161        7     1 nonwhite   male    new     no     no    0    0    0    1
## 162       23     0    white   male   lose     no    yes    1    1    1    1
## 163        6     1    white   male   lose     no     no    1    0    0    0
## 164        1     1 nonwhite female reentr    yes    yes    0    0    0    0
## 165       43     1 nonwhite   male   lose    yes     no    1    1    0    0
## 166        3     1    white female reentr    yes     no    1    0    1    0
## 167       26     1    white female  leave     no    yes    1    1    1    0
## 168        0     1    white female    new     no     no    0    0    0    0
## 169        3     0    white female  leave    yes     no    1    0    0    1
## 170       78     1    white   male   lose     no     no    1    0    0    0
## 171       13     1    white   male reentr     no     no    0    0    0    0
## 172       13     1    white female   lose     no     no    1    0    0    0
## 173       52     1    white female    new     no     no    0    0    0    0
## 174       52     0    white   male   lose     no     no    1    1    0    0
## 175        2     0    white female reentr    yes     no    0    0    0    0
## 176      104     1    white female  leave     no     no    0    0    0    0
## 177        7     1    white female  leave     no    yes    1    1    0    0
## 178        4     1    white   male reentr    yes     no    0    0    0    0
## 179       16     1    white female reentr    yes     no    0    1    0    0
## 180       35     1 nonwhite female reentr     no     no    1    0    1    1
## 181        6     1    white   male  leave     no     no    0    0    0    0
## 182       17     0    white   male  leave     no     no    0    0    0    0
## 183        4     0 nonwhite female   lose     no     no    1    0    0    1
## 184        5     1    white   male   lose     no     no    1    1    1    0
## 185       38     1    white   male   lose    yes     no    1    1    1    0
## 186        4     0    white female reentr    yes     no    1    0    0    1
## 187       12     1    white female  leave    yes    yes    1    1    1    0
## 188       30     1    white   male reentr     no     no    1    0    0    0
## 189        4     0    white female reentr     no     no    0    0    0    0
## 190        1     0 nonwhite female reentr     no     no    1    0    1    0
## 191        6     1    white   male    new     no     no    0    0    0    0
## 192        2     1    white   male  leave    yes     no    1    0    0    0
## 193       25     0    white   male reentr     no     no    1    1    1    1
## 194        9     0    white   male   lose     no     no    1    1    1    1
## 195        4     1    white female reentr     no     no    0    0    0    0
## 196       61     0    white   male reentr     no    yes    1    1    1    1
## 197        3     1    white female    new    yes     no    0    0    0    0
## 198       22     1    white   male reentr     no     no    0    1    0    0
## 199       11     1    white   male   lose     no     no    1    0    0    0
## 200        2     1    white   male   lose     no     no    0    1    0    0
## 201       48     0    white   male   lose     no    yes    1    1    1    1
## 202        1     1    white   male   lose     no     no    1    0    0    0
## 203       16     1    white female reentr     no    yes    1    1    0    1
## 204       15     0    white   male   lose    yes    yes    1    1    1    1
## 205       26     0    white   male   lose     no    yes    1    1    1    1
## 206       16     0    white   male   lose     no    yes    1    1    1    1
## 207        8     1    white female reentr     no     no    1    1    1    0
## 208        8     0    white   male  leave    yes    yes    1    1    1    1
## 209        1     1    white female reentr     no    yes    0    0    0    0
## 210        7     0    white   male  leave     no    yes    1    1    1    1
## 211        7     0    white female   lose     no    yes    1    1    1    1
## 212       43     0    white female   lose     no    yes    1    1    1    1
## 213        4     1    white female  leave    yes     no    1    0    0    0
## 214       61     0    white   male   lose     no     no    1    1    1    1
## 215       39     0    white   male  leave     no    yes    1    1    0    0
## 216        4     1 nonwhite female reentr     no     no    0    1    0    0
## 217        1     1 nonwhite female  leave     no     no    0    0    0    0
## 218        2     0    white   male   lose     no     no    1    0    0    1
## 219       39     1    white   male  leave    yes    yes    1    0    0    0
## 220       12     1    white   male   lose    yes    yes    1    0    0    0
## 221        4     0    white   male  leave    yes     no    1    0    1    0
## 222        8     1    white female reentr     no     no    0    1    0    0
## 223       10     0    white   male   lose     no     no    0    0    0    0
## 224        7     1 nonwhite   male  leave     no     no    1    0    0    0
## 225        4     0    white female   lose     no     no    0    0    0    0
## 226        1     1    white   male   lose     no     no    0    0    1    1
## 227        7     1 nonwhite female reentr    yes     no    1    0    0    0
## 228        3     1 nonwhite   male reentr     no     no    1    0    0    0
## 229       12     0    white female  leave     no    yes    1    1    1    0
## 230        3     1    white female  leave    yes     no    1    0    1    0
## 231        4     0    white   male  leave    yes    yes    1    0    0    1
## 232      117     0    white   male   lose     no    yes    1    1    1    1
## 233       35     0 nonwhite female reentr     no     no    1    1    1    1
## 234        6     0    white   male  leave    yes     no    1    0    0    0
## 235        9     0 nonwhite female    new     no     no    0    0    0    0
## 236      100     0    white   male   lose     no    yes    1    1    1    1
## 237       26     1    white female    new    yes     no    0    0    0    0
## 238        8     1    white   male reentr     no     no    0    1    0    0
## 239        9     0    white   male   lose     no     no    1    1    1    1
## 240        2     1    white   male  leave    yes     no    0    1    0    0
## 241       16     1    white female    new     no     no    0    0    0    0
## 242        8     1 nonwhite   male   lose     no     no    1    1    0    0
## 243        4     1    white   male   lose    yes     no    0    1    0    0
## 244      109     0 nonwhite female   lose     no    yes    1    1    1    1
## 245       49     0 nonwhite   male reentr     no    yes    1    1    1    1
## 246        1     0 nonwhite   male reentr    yes     no    0    0    0    0
## 247       12     1 nonwhite female reentr    yes     no    1    0    0    0
## 248       61     0 nonwhite   male   lose     no    yes    1    1    1    1
## 249        2     1 nonwhite   male   lose     no     no    1    0    1    1
## 250       17     0 nonwhite female   lose     no     no    1    1    1    1
## 251       60     1    white female   lose     no     no    1    1    1    0
## 252      112     1    white female reentr     no     no    1    1    1    0
## 253       52     1    white female   lose     no     no    1    0    1    0
## 254       17     0    white   male   lose    yes     no    1    1    1    1
## 255        8     0 nonwhite   male    new     no     no    1    1    0    0
## 256      104     1 nonwhite female    new    yes    yes    1    0    0    0
## 257       65     0 nonwhite   male   lose     no     no    1    1    1    1
## 258        6     1    white female   lose     no    yes    1    1    0    0
## 259       29     0    white   male   lose     no    yes    1    1    1    1
## 260        8     1 nonwhite   male   lose    yes     no    0    1    0    0
## 261       26     1    white   male  leave    yes     no    1    1    0    0
## 262        1     1    white   male  leave    yes     no    0    0    0    0
## 263       16     1    white   male reentr     no    yes    1    1    0    0
## 264        6     1    white   male   lose    yes    yes    0    1    0    0
## 265       30     0    white   male   lose     no     no    1    1    1    0
## 266        3     1    white female  leave     no     no    0    0    0    0
## 267       12     1    white female   lose     no     no    0    0    0    0
## 268       12     1    white   male  leave     no     no    1    0    1    0
## 269        8     1    white   male  leave     no     no    1    0    1    0
## 270       13     1    white female    new    yes     no    1    0    1    0
## 271       16     1    white   male   lose    yes     no    1    1    0    0
## 272        6     1    white   male   lose    yes     no    1    1    0    1
## 273       43     0    white   male  leave     no     no    1    1    1    1
## 274       52     0    white female reentr    yes     no    0    0    0    0
## 275       12     0    white female    new     no     no    0    0    0    0
## 276        6     0    white female reentr     no     no    0    0    0    0
## 277        1     0    white   male reentr    yes     no    0    0    0    0
## 278       13     0    white female   lose     no     no    1    1    1    1
## 279       47     0 nonwhite   male   lose     no     no    1    1    1    0
## 280        4     1    white   male reentr    yes     no    0    0    0    0
## 281        4     0    white   male  leave     no     no    1    0    0    1
## 282        3     1    white   male   lose     no     no    1    0    0    0
## 283       12     1    white   male reentr     no    yes    0    1    0    0
## 284       12     1    white female  leave    yes     no    1    0    0    0
## 285        3     1    white   male  leave     no     no    0    1    0    0
## 286       23     0    white female reentr     no     no    0    0    0    0
## 287        2     0 nonwhite female  leave    yes     no    1    0    0    1
## 288       39     0    white   male   lose     no     no    1    1    1    1
## 289       39     0    white   male   lose     no     no    1    1    1    1
## 290        2     1    white   male    new     no     no    0    0    0    0
## 291       24     0    white female reentr     no    yes    1    1    1    1
## 292       43     1    white   male   lose    yes     no    1    0    0    0
## 293        6     0 nonwhite female reentr    yes     no    1    1    0    0
## 294        7     1 nonwhite female reentr    yes     no    0    0    0    0
## 295        4     1 nonwhite   male reentr    yes     no    1    0    0    0
## 296        2     1    white female  leave     no     no    0    0    0    0
## 297        1     1    white female reentr     no     no    0    0    0    0
## 298        1     1 nonwhite female   lose     no     no    0    0    0    0
## 299       17     0 nonwhite female reentr     no     no    0    0    0    0
## 300      104     0 nonwhite female reentr     no     no    1    0    0    1
## 301        1     1    white female   lose     no     no    0    0    0    0
## 302        4     1    white   male    new     no     no    0    1    0    0
## 303        8     1    white female reentr    yes     no    0    1    0    0
## 304       35     0    white   male   lose    yes     no    1    1    1    1
## 305        1     1    white female reentr     no     no    1    0    0    0
## 306       16     1 nonwhite female  leave    yes    yes    1    0    1    1
## 307       15     0    white female   lose     no     no    1    1    1    1
## 308       15     0    white female reentr     no     no    1    1    1    1
## 309       11     0    white female reentr     no     no    1    1    1    1
## 310        1     1    white female reentr     no     no    0    0    0    0
## 311        2     0    white female    new     no     no    0    0    0    0
## 312       61     0    white   male  leave    yes     no    1    1    1    1
## 313       39     1 nonwhite   male   lose     no     no    1    0    0    0
## 314       11     0 nonwhite   male   lose     no     no    1    1    1    0
## 315        4     0    white   male  leave    yes    yes    1    0    1    0
## 316       13     0    white female reentr    yes     no    1    1    1    1
## 317       20     1    white   male  leave     no     no    1    1    1    0
## 318       15     0 nonwhite   male  leave     no    yes    1    1    1    1
## 319       69     1    white   male   lose    yes    yes    1    1    0    0
## 320       20     1    white female reentr     no     no    0    0    0    0
## 321        4     0    white   male   lose    yes     no    1    0    0    1
## 322       43     1    white   male   lose     no     no    1    0    1    0
## 323       20     1    white female reentr     no     no    0    0    0    0
## 324       11     1    white   male   lose    yes    yes    1    0    1    0
## 325        3     1    white female    new    yes     no    0    0    0    0
## 326        4     1    white   male reentr     no     no    0    0    0    0
## 327       10     1    white   male   lose    yes    yes    1    1    0    0
## 328        8     0    white female reentr    yes     no    0    0    0    0
## 329        1     1    white female reentr    yes     no    0    0    0    0
## 330        8     1 nonwhite female   lose     no     no    1    0    0    0
## 331       35     0    white   male   lose    yes     no    1    1    1    1
## 332       12     1    white   male reentr     no     no    0    0    0    0
## 333       52     0 nonwhite female reentr     no     no    1    0    0    1
## 334       25     0 nonwhite female reentr     no     no    1    1    1    1
## 335       26     0 nonwhite   male    new     no     no    1    0    0    1
## 336       18     0 nonwhite female  leave     no     no    1    1    1    1
## 337        2     1 nonwhite   male   lose     no     no    1    0    0    0
## 338       28     0 nonwhite female   lose    yes     no    1    1    1    1
## 339        2     1    white   male   lose     no     no    0    0    0    0
## 340       11     1    white   male   lose     no     no    1    0    1    0
## 341        1     1 nonwhite female reentr     no     no    0    0    0    0
## 342        2     1 nonwhite   male   lose     no     no    1    0    1    0
## 343       17     1    white   male   lose    yes     no    1    0    0    0
## 344        6     1    white   male   lose     no     no    1    0    0    0
## 345        2     1    white female   lose     no     no    0    0    0    0
## 346        1     1    white female reentr    yes     no    1    0    1    0
## 347        8     1    white female reentr     no     no    1    0    0    0
## 348        7     0    white   male   lose     no     no    1    1    1    1
## 349       14     1 nonwhite female  leave     no    yes    1    1    1    0
## 350        9     0 nonwhite female  leave    yes    yes    0    1    0    0
## 351        1     1    white   male   lose    yes    yes    1    0    1    0
## 352        1     0    white female   lose    yes     no    1    0    0    1
## 353       17     1 nonwhite female reentr    yes     no    1    1    0    0
## 354       29     0 nonwhite   male   lose     no    yes    1    1    1    1
## 355        4     1    white   male    new     no     no    0    0    0    0
## 356        9     0 nonwhite   male  leave    yes     no    0    0    0    0
## 357       26     1    white   male  leave     no     no    0    1    0    0
## 358       39     0    white female  leave     no     no    1    1    1    1
## 359        3     0 nonwhite   male   lose     no     no    1    0    0    1
## 360       17     0    white   male  leave     no     no    1    1    1    1
## 361       19     0 nonwhite   male   lose     no     no    1    0    0    1
## 362       29     0 nonwhite   male   lose     no    yes    1    1    1    1
## 363        2     1    white female   lose     no     no    1    0    1    0
## 364       13     0 nonwhite   male   lose    yes    yes    1    0    0    1
## 365       30     1 nonwhite   male reentr     no     no    1    0    0    0
## 366        4     1 nonwhite   male    new    yes    yes    0    0    0    0
## 367        1     0    white female   lose     no     no    0    0    0    0
## 368        5     0 nonwhite   male   lose     no     no    1    1    1    0
## 369        6     0 nonwhite   male reentr    yes    yes    0    1    0    0
## 370        1     1    white female   lose     no     no    0    0    0    0
## 371        4     1    white   male reentr    yes    yes    1    0    0    0
## 372       15     1    white   male  leave     no     no    1    1    0    0
## 373        2     1    white   male  leave    yes     no    1    0    0    0
## 374        6     1    white female   lose    yes     no    1    0    0    0
## 375        2     0    white   male  leave     no     no    1    0    0    1
## 376       29     0    white   male   lose     no     no    1    1    1    1
## 377        1     1    white   male reentr     no     no    0    0    0    0
## 378        2     1    white female reentr    yes     no    1    0    0    0
## 379       12     1    white female   lose     no     no    0    1    0    0
## 380       35     1    white   male reentr     no     no    1    0    1    0
## 381       13     1    white   male   lose     no    yes    1    1    0    0
## 382       17     0    white   male   lose    yes     no    1    1    1    1
## 383        2     1    white female reentr    yes     no    0    1    0    0
## 384        0     1    white   male  leave     no     no    0    1    0    0
## 385        1     1    white   male   lose     no     no    1    0    1    0
## 386       10     1    white female   lose    yes    yes    0    1    0    0
## 387       13     1 nonwhite   male reentr    yes    yes    1    0    0    0
## 388        6     1    white female reentr    yes    yes    1    0    0    0
## 389        1     1    white female   lose     no     no    0    0    0    0
## 390        6     1    white   male    new     no     no    1    1    0    0
## 391       52     1    white   male   lose    yes     no    1    0    0    1
## 392        8     1    white   male    new    yes     no    1    0    0    0
## 393       12     0    white female    new     no     no    1    1    0    0
## 394       26     1 nonwhite   male  leave     no    yes    1    1    0    0
## 395       52     1    white female reentr     no    yes    1    0    0    0
## 396        9     1 nonwhite   male   lose    yes     no    1    0    0    0
## 397       12     0    white   male   lose     no     no    1    0    0    1
## 398       22     0    white female   lose     no     no    1    1    1    1
## 399       16     1    white female reentr    yes     no    1    1    1    0
## 400        2     1    white female reentr     no     no    0    1    0    0
## 401       61     0    white female reentr     no     no    0    0    0    0
## 402        2     1 nonwhite   male  leave    yes     no    1    0    0    0
## 403       52     0    white female reentr     no     no    1    0    1    0
## 404        9     1 nonwhite female    new     no     no    1    1    0    0
## 405       39     1    white   male  leave     no     no    1    1    1    0
## 406       26     1    white   male   lose     no    yes    1    1    1    0
## 407        8     1    white   male  leave     no     no    1    0    0    0
## 408        3     1    white   male   lose     no     no    0    1    0    0
## 409        5     1    white female   lose     no     no    1    1    0    0
## 410        6     0 nonwhite   male reentr    yes     no    1    0    0    1
## 411       52     1 nonwhite   male reentr    yes     no    1    0    0    0
## 412        3     0 nonwhite female reentr     no     no    1    0    0    1
## 413        4     1 nonwhite   male reentr     no     no    1    0    0    0
## 414       20     1 nonwhite female  leave     no     no    1    1    1    0
## 415        2     1 nonwhite   male reentr     no     no    1    0    0    0
## 416        3     0 nonwhite   male   lose     no     no    1    0    0    1
## 417       52     1    white   male   lose    yes    yes    1    0    0    0
## 418       21     0    white   male reentr     no     no    1    1    1    1
## 419       65     0    white   male  leave     no     no    1    1    1    1
## 420        4     0    white female    new     no     no    1    0    0    1
## 421        3     1    white   male reentr    yes     no    1    0    1    0
## 422        4     1    white   male  leave    yes     no    1    0    0    0
## 423       52     0    white female   lose     no     no    1    0    0    1
## 424       16     0    white female reentr    yes    yes    1    1    0    0
## 425       86     1    white   male   lose     no    yes    1    1    1    0
## 426       12     1    white   male   lose    yes    yes    1    0    0    0
## 427        1     1    white   male  leave     no     no    1    0    0    0
## 428       17     0    white female  leave     no     no    1    1    1    1
## 429        4     1    white   male  leave     no     no    0    0    0    0
## 430       34     0    white   male   lose     no     no    1    1    1    0
## 431        1     1    white female reentr     no     no    1    0    0    0
## 432       38     0    white   male   lose    yes     no    1    1    1    0
## 433       21     0    white   male  leave     no    yes    1    1    1    1
## 434       60     1    white female   lose     no     no    0    0    0    0
## 435        2     1    white   male   lose    yes     no    1    0    1    0
## 436       14     0    white   male   lose     no    yes    1    1    1    1
## 437        1     1    white   male   lose     no     no    0    0    0    0
## 438        8     1 nonwhite female  leave     no     no    1    1    0    0
## 439        1     0    white female reentr    yes     no    1    0    0    1
## 440        4     0    white   male   lose     no     no    1    0    0    1
## 441        3     1 nonwhite   male  leave     no     no    0    1    0    0
## 442        2     0    white   male reentr     no     no    0    0    0    0
## 443        4     1    white female   lose     no     no    1    0    0    0
## 444       30     1    white female reentr    yes     no    1    0    0    0
## 445        6     0    white   male reentr     no     no    0    0    0    0
## 446        7     1    white   male  leave     no     no    1    1    1    0
## 447        6     1    white female  leave     no     no    1    1    0    0
## 448       43     0 nonwhite female   lose     no     no    1    1    1    0
## 449       12     1 nonwhite female reentr     no     no    1    1    1    0
## 450       52     1    white female  leave     no     no    1    0    1    0
## 451       12     1 nonwhite female reentr     no     no    1    1    1    0
## 452       21     0    white   male reentr     no     no    0    0    0    0
##     nobs
## 1      1
## 2      2
## 3      1
## 4      1
## 5      1
## 6      1
## 7      4
## 8      1
## 9      3
## 10     1
## 11     2
## 12     1
## 13     4
## 14     4
## 15     1
## 16     1
## 17     2
## 18     2
## 19     4
## 20     1
## 21     1
## 22     1
## 23     3
## 24     1
## 25     1
## 26     1
## 27     1
## 28     3
## 29     1
## 30     1
## 31     3
## 32     3
## 33     1
## 34     3
## 35     2
## 36     1
## 37     3
## 38     2
## 39     4
## 40     1
## 41     1
## 42     4
## 43     2
## 44     1
## 45     4
## 46     1
## 47     1
## 48     2
## 49     2
## 50     1
## 51     1
## 52     4
## 53     1
## 54     1
## 55     4
## 56     2
## 57     1
## 58     1
## 59     1
## 60     1
## 61     2
## 62     2
## 63     1
## 64     2
## 65     3
## 66     2
## 67     3
## 68     2
## 69     4
## 70     1
## 71     1
## 72     1
## 73     1
## 74     1
## 75     1
## 76     1
## 77     1
## 78     3
## 79     1
## 80     1
## 81     3
## 82     1
## 83     2
## 84     3
## 85     2
## 86     4
## 87     1
## 88     3
## 89     1
## 90     4
## 91     4
## 92     1
## 93     1
## 94     1
## 95     3
## 96     1
## 97     1
## 98     2
## 99     1
## 100    2
## 101    2
## 102    1
## 103    1
## 104    2
## 105    1
## 106    1
## 107    1
## 108    1
## 109    1
## 110    3
## 111    1
## 112    4
## 113    2
## 114    2
## 115    1
## 116    3
## 117    3
## 118    4
## 119    1
## 120    1
## 121    1
## 122    1
## 123    1
## 124    1
## 125    1
## 126    1
## 127    1
## 128    1
## 129    1
## 130    1
## 131    1
## 132    1
## 133    1
## 134    3
## 135    1
## 136    1
## 137    1
## 138    1
## 139    2
## 140    3
## 141    3
## 142    1
## 143    1
## 144    2
## 145    3
## 146    1
## 147    1
## 148    1
## 149    1
## 150    1
## 151    4
## 152    2
## 153    3
## 154    4
## 155    3
## 156    1
## 157    4
## 158    4
## 159    1
## 160    4
## 161    2
## 162    4
## 163    1
## 164    1
## 165    2
## 166    1
## 167    3
## 168    1
## 169    1
## 170    1
## 171    2
## 172    1
## 173    1
## 174    2
## 175    1
## 176    1
## 177    2
## 178    1
## 179    1
## 180    1
## 181    2
## 182    4
## 183    1
## 184    2
## 185    3
## 186    1
## 187    3
## 188    1
## 189    1
## 190    1
## 191    1
## 192    1
## 193    4
## 194    2
## 195    1
## 196    3
## 197    1
## 198    1
## 199    1
## 200    1
## 201    4
## 202    1
## 203    2
## 204    4
## 205    4
## 206    4
## 207    2
## 208    2
## 209    1
## 210    2
## 211    2
## 212    4
## 213    1
## 214    3
## 215    2
## 216    1
## 217    1
## 218    1
## 219    1
## 220    1
## 221    1
## 222    1
## 223    3
## 224    1
## 225    1
## 226    1
## 227    1
## 228    1
## 229    3
## 230    1
## 231    1
## 232    4
## 233    4
## 234    1
## 235    2
## 236    4
## 237    1
## 238    1
## 239    2
## 240    1
## 241    1
## 242    2
## 243    1
## 244    2
## 245    3
## 246    1
## 247    1
## 248    3
## 249    1
## 250    4
## 251    3
## 252    3
## 253    1
## 254    4
## 255    2
## 256    1
## 257    4
## 258    2
## 259    4
## 260    1
## 261    2
## 262    1
## 263    2
## 264    1
## 265    3
## 266    1
## 267    3
## 268    1
## 269    1
## 270    1
## 271    2
## 272    1
## 273    4
## 274    1
## 275    1
## 276    2
## 277    1
## 278    3
## 279    2
## 280    1
## 281    1
## 282    1
## 283    1
## 284    1
## 285    1
## 286    4
## 287    1
## 288    4
## 289    4
## 290    1
## 291    4
## 292    1
## 293    2
## 294    2
## 295    1
## 296    1
## 297    1
## 298    1
## 299    2
## 300    1
## 301    1
## 302    1
## 303    1
## 304    4
## 305    1
## 306    1
## 307    2
## 308    4
## 309    3
## 310    1
## 311    1
## 312    3
## 313    1
## 314    3
## 315    1
## 316    2
## 317    3
## 318    4
## 319    2
## 320    2
## 321    1
## 322    1
## 323    3
## 324    1
## 325    1
## 326    1
## 327    2
## 328    1
## 329    1
## 330    1
## 331    4
## 332    1
## 333    1
## 334    4
## 335    1
## 336    2
## 337    1
## 338    3
## 339    1
## 340    1
## 341    1
## 342    1
## 343    1
## 344    1
## 345    1
## 346    1
## 347    1
## 348    2
## 349    3
## 350    1
## 351    1
## 352    1
## 353    2
## 354    4
## 355    1
## 356    2
## 357    1
## 358    4
## 359    1
## 360    2
## 361    1
## 362    4
## 363    1
## 364    1
## 365    1
## 366    1
## 367    1
## 368    2
## 369    1
## 370    1
## 371    1
## 372    2
## 373    1
## 374    1
## 375    1
## 376    4
## 377    1
## 378    1
## 379    1
## 380    1
## 381    2
## 382    4
## 383    1
## 384    1
## 385    1
## 386    1
## 387    1
## 388    1
## 389    1
## 390    2
## 391    1
## 392    1
## 393    2
## 394    2
## 395    1
## 396    1
## 397    1
## 398    4
## 399    3
## 400    1
## 401    3
## 402    1
## 403    1
## 404    2
## 405    2
## 406    2
## 407    2
## 408    1
## 409    2
## 410    1
## 411    1
## 412    1
## 413    1
## 414    3
## 415    1
## 416    1
## 417    1
## 418    4
## 419    4
## 420    1
## 421    1
## 422    1
## 423    1
## 424    2
## 425    3
## 426    1
## 427    1
## 428    4
## 429    1
## 430    3
## 431    1
## 432    3
## 433    4
## 434    3
## 435    1
## 436    4
## 437    1
## 438    2
## 439    1
## 440    1
## 441    1
## 442    1
## 443    1
## 444    1
## 445    2
## 446    2
## 447    2
## 448    2
## 449    2
## 450    1
## 451    3
## 452    3</code></pre>
<pre class="r"><code>head(Unemployment)</code></pre>
<pre><code>##   duration spell     race    sex reason search pubemp ftp1 ftp2 ftp3 ftp4 nobs
## 1        4     1    white   male reentr    yes    yes    1    0    0    0    1
## 2        7     0    white   male   lose     no     no    1    1    1    1    2
## 3        1     0 nonwhite   male   lose     no     no    0    0    0    0    1
## 4        1     1 nonwhite   male reentr     no     no    0    1    0    0    1
## 5        3     1 nonwhite female reentr     no     no    0    0    0    0    1
## 6        1     1    white female reentr     no     no    0    0    0    0    1</code></pre>
<div id="ols-regression" class="section level2">
<h2>OLS regression</h2>
<pre class="r"><code>summary(Unemployment$duration)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    0.00    4.00   10.00   18.51   22.25  117.00</code></pre>
<pre class="r"><code>plot(Unemployment$duration)</code></pre>
<p><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<pre class="r"><code>boxplot(Unemployment$duration)</code></pre>
<p><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-3-2.png" width="672" /></p>
<pre class="r"><code>plot(Unemployment$duration ~ Unemployment$sex)</code></pre>
<p><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-3-3.png" width="672" /></p>
<pre class="r"><code>plot(Unemployment$duration ~ Unemployment$race)</code></pre>
<p><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-3-4.png" width="672" /></p>
<pre class="r"><code>t.test(Unemployment$duration ~ Unemployment$sex)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  Unemployment$duration by Unemployment$sex
## t = 0.61614, df = 435.97, p-value = 0.5381
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -2.947326  5.639101
## sample estimates:
##   mean in group male mean in group female 
##             19.13636             17.79048</code></pre>
<pre class="r"><code>t.test(Unemployment$duration ~ Unemployment$race)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  Unemployment$duration by Unemployment$race
## t = 0.2089, df = 208.95, p-value = 0.8347
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -4.301055  5.320624
## sample estimates:
## mean in group nonwhite    mean in group white 
##               18.88889               18.37910</code></pre>
<pre class="r"><code>t.test(Unemployment$duration ~ Unemployment$search)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  Unemployment$duration by Unemployment$search
## t = 0.3496, df = 266.6, p-value = 0.7269
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -3.841640  5.500454
## sample estimates:
##  mean in group no mean in group yes 
##          18.77346          17.94406</code></pre>
<pre class="r"><code>t.test(Unemployment$duration ~ Unemployment$pubemp)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  Unemployment$duration by Unemployment$pubemp
## t = -3.0635, df = 119.58, p-value = 0.002704
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -15.704693  -3.373809
## sample estimates:
##  mean in group no mean in group yes 
##          16.56944          26.10870</code></pre>
<pre class="r"><code>OLS1 &lt;- lm(duration ~ race + pubemp , data=Unemployment)
summary(OLS1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = duration ~ race + pubemp, data = Unemployment)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -25.302 -14.302  -8.771   3.499  96.499 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  16.7708     2.1907   7.656 1.19e-13 ***
## racewhite    -0.2695     2.4507  -0.110 0.912475    
## pubempyes     9.5312     2.6660   3.575 0.000388 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 22.81 on 449 degrees of freedom
## Multiple R-squared:  0.02777,    Adjusted R-squared:  0.02344 
## F-statistic: 6.412 on 2 and 449 DF,  p-value: 0.001796</code></pre>
<pre class="r"><code>plot(OLS1)</code></pre>
<p><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-3-5.png" width="672" /><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-3-6.png" width="672" /><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-3-7.png" width="672" /><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-3-8.png" width="672" /></p>
</div>
<div id="survival-analysis" class="section level2">
<h2>Survival analysis</h2>
</div>
<div id="data-handling" class="section level2">
<h2>Data Handling</h2>
<p>The duration data are of specific format.</p>
<p>Function <code>Surv(time, status)</code> from <code>survival</code>package create data possibly censored.</p>
<ul>
<li><code>time</code>: real observed time</li>
<li><code>status</code>: dummy for censored duration (<code>T</code>) or not(<code>F</code>)</li>
</ul>
<p>In presence of time-varying covariates, we use: <code>Surv(start,stop,event,data=mydata)</code>, avec <code>start</code>and <code>stop</code> the beginning and the end of the time at risk, and <code>status</code> is 1 when the event is observed.</p>
</div>
<div id="survival-curves-life-table" class="section level2">
<h2>Survival curves &amp; Life Table</h2>
<p>The function <code>survfit()</code> computes Kaplan-Meier survival estimate.</p>
<p>Its main arguments include:</p>
<ul>
<li>a survival time data (from <code>Surv()</code>)</li>
<li>the data set containing the variables</li>
</ul>
<p>To compute survival curves:</p>
<ol style="list-style-type: decimal">
<li>Simple survival curve that doesn’t consider any different groupings</li>
</ol>
<div id="life-table" class="section level3">
<h3>Life Table</h3>
<pre class="r"><code>Surv_time &lt;- with( Unemployment, Surv(duration, spell))

sfit1 &lt;- survfit(Surv_time~1, data = Unemployment)
sfit1</code></pre>
<pre><code>## Call: survfit(formula = Surv_time ~ 1, data = Unemployment)
## 
##       n  events  median 0.95LCL 0.95UCL 
##     452     256      18      15      26</code></pre>
<pre class="r"><code>surv_summary(sfit1)</code></pre>
<pre><code>##    time n.risk n.event n.censor       surv     std.err     upper      lower
## 1     0    452       2        0 0.99557522 0.003135736 1.0000000 0.98947525
## 2     1    450      32       14 0.92477876 0.013414735 0.9494159 0.90078097
## 3     2    404      28        9 0.86068518 0.019086175 0.8934917 0.82908326
## 4     3    367      18        8 0.81847174 0.022468109 0.8553199 0.78321104
## 5     4    341      19       14 0.77286774 0.026035642 0.8133299 0.73441849
## 6     5    308       5        3 0.76032119 0.027044990 0.8017110 0.72106822
## 7     6    300      13        7 0.72737394 0.029705533 0.7709800 0.68623417
## 8     7    280      11        6 0.69879853 0.032069647 0.7441315 0.65622724
## 9     8    263      17        6 0.65362905 0.035933571 0.7013230 0.60917859
## 10    9    240       5        8 0.64001177 0.037146655 0.6883467 0.59507085
## 11   10    227       4        3 0.62873403 0.038195452 0.6776087 0.58338457
## 12   11    220       3        5 0.62016039 0.039009396 0.6694357 0.57451208
## 13   12    212      15       11 0.57628112 0.043369275 0.6274085 0.52932011
## 14   13    186       7        4 0.55459312 0.045729007 0.6065953 0.50704893
## 15   14    175       2        1 0.54825491 0.046445701 0.6005058 0.50055047
## 16   15    172       1        6 0.54506738 0.046810286 0.5974412 0.49728482
## 17   16    165      11        3 0.50872956 0.051226002 0.5624587 0.46013293
## 18   17    151       2       11 0.50199142 0.052086430 0.5559457 0.45327341
## 19   18    138       1        1 0.49835380 0.052591724 0.5524639 0.44954339
## 20   19    136       0        3 0.49835380 0.052591724 0.5524639 0.44954339
## 21   20    133       6        1 0.47587167 0.055866879 0.5309380 0.42651654
## 22   21    126       2        5 0.46831815 0.057001021 0.5236732 0.41881443
## 23   22    119       4        2 0.45257637 0.059509724 0.5085652 0.40275144
## 24   23    113       0        3 0.45257637 0.059509724 0.5085652 0.40275144
## 25   24    110       0        1 0.45257637 0.059509724 0.5085652 0.40275144
## 26   25    109       0        4 0.45257637 0.059509724 0.5085652 0.40275144
## 27   26    105       8        5 0.41809436 0.065778994 0.4756259 0.36752182
## 28   27     92       0        1 0.41809436 0.065778994 0.4756259 0.36752182
## 29   28     91       0        1 0.41809436 0.065778994 0.4756259 0.36752182
## 30   29     90       0        4 0.41809436 0.065778994 0.4756259 0.36752182
## 31   30     86       3        1 0.40350967 0.068899650 0.4618505 0.35253842
## 32   34     82       0        1 0.40350967 0.068899650 0.4618505 0.35253842
## 33   35     81       4        4 0.38358327 0.073406374 0.4429383 0.33218195
## 34   38     73       2        1 0.37307414 0.075989293 0.4329895 0.32144964
## 35   39     70       4        4 0.35175561 0.081487260 0.4126702 0.29983267
## 36   43     62       3        3 0.33473518 0.086372993 0.3964808 0.28260545
## 37   47     56       0        1 0.33473518 0.086372993 0.3964808 0.28260545
## 38   48     55       0        3 0.33473518 0.086372993 0.3964808 0.28260545
## 39   49     52       0        1 0.33473518 0.086372993 0.3964808 0.28260545
## 40   52     51       8        5 0.28222770 0.105395753 0.3469866 0.22955492
## 41   56     38       3        1 0.25994657 0.115602352 0.3260506 0.20724458
## 42   58     34       0        1 0.25994657 0.115602352 0.3260506 0.20724458
## 43   60     33       2        0 0.24419223 0.123769697 0.3112324 0.19159267
## 44   61     31       0        8 0.24419223 0.123769697 0.3112324 0.19159267
## 45   65     23       0        6 0.24419223 0.123769697 0.3112324 0.19159267
## 46   69     17       1        0 0.22982798 0.137823832 0.3011055 0.17542321
## 47   78     16       1        0 0.21546373 0.152190917 0.2903483 0.15989285
## 48   86     15       1        0 0.20109948 0.167104698 0.2790299 0.14493430
## 49  100     14       0        1 0.20109948 0.167104698 0.2790299 0.14493430
## 50  104     13       6        2 0.10828434 0.306362605 0.1973976 0.05940039
## 51  108      5       1        0 0.08662747 0.379286232 0.1821817 0.04119140
## 52  109      4       0        1 0.08662747 0.379286232 0.1821817 0.04119140
## 53  112      3       1        0 0.05775165 0.557247443 0.1721449 0.01937468
## 54  113      2       0        1 0.05775165 0.557247443 0.1721449 0.01937468
## 55  117      1       0        1 0.05775165 0.557247443 0.1721449 0.01937468</code></pre>
</div>
<div id="survival-curve-ci" class="section level3">
<h3>Survival curve &amp; CI</h3>
<p>Information about the survival curves</p>
<pre class="r"><code>attr(surv_summary(sfit1), &quot;table&quot;)</code></pre>
<pre><code>##            summary(x)$table
## records          452.000000
## n.max            452.000000
## n.start          452.000000
## events           256.000000
## *rmean            38.567702
## *se(rmean)         2.531508
## median            18.000000
## 0.95LCL           15.000000
## 0.95UCL           26.000000</code></pre>
<pre class="r"><code>plot(sfit1)
ggsurvplot(sfit1, conf.int=TRUE, pval=TRUE, risk.table=TRUE, 
           palette=c(&quot;dodgerblue2&quot;, &quot;orchid2&quot;), 
           title=&quot;KM Curve for Job Duration Survival&quot;, 
           risk.table.height=.15)</code></pre>
<pre><code>## Warning in .pvalue(fit, data = data, method = method, pval = pval, pval.coord = pval.coord, : There are no survival curves to be compared. 
##  This is a null model.</code></pre>
<p><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-6-1.png" width="672" /><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-6-2.png" width="672" /></p>
</div>
</div>
<div id="different-survival-curves-depending-on-sex" class="section level2">
<h2>Different survival curves depending on sex</h2>
<pre class="r"><code>addmargins( table(Unemployment$sex))</code></pre>
<pre><code>## 
##   male female    Sum 
##    242    210    452</code></pre>
<pre class="r"><code>sfit2 &lt;- survfit(Surv_time~sex, data = Unemployment)
sfit2</code></pre>
<pre><code>## Call: survfit(formula = Surv_time ~ sex, data = Unemployment)
## 
##              n events median 0.95LCL 0.95UCL
## sex=male   242    134     22      13      35
## sex=female 210    122     16      13      22</code></pre>
<pre class="r"><code>surv_summary(sfit2)</code></pre>
<pre><code>## Warning in .get_data(x, data = data): The `data` argument is not provided. Data
## will be extracted from model fit.</code></pre>
<pre><code>##    time n.risk n.event n.censor       surv     std.err     upper      lower
## 1     0    242       1        0 0.99586777 0.004140796 1.0000000 0.98781820
## 2     1    241      14        7 0.93801653 0.016524374 0.9688935 0.90812351
## 3     2    220      14        5 0.87832457 0.024124040 0.9208512 0.83776191
## 4     3    201      10        3 0.83462683 0.029024938 0.8834834 0.78847199
## 5     4    188      13        7 0.77691327 0.035179310 0.8323715 0.72515001
## 6     5    168       4        2 0.75841534 0.037185533 0.8157545 0.70510651
## 7     6    162       7        5 0.72564430 0.040761958 0.7859962 0.66992649
## 8     7    150       6        4 0.69661853 0.044037655 0.7594163 0.63901360
## 9     8    140       7        4 0.66178760 0.048117095 0.7272370 0.60222847
## 10    9    129       3        5 0.64639719 0.049998248 0.7129483 0.58605838
## 11   10    121       2        2 0.63571294 0.051368505 0.7030497 0.57482560
## 12   11    117       3        2 0.61941261 0.053513032 0.6879081 0.55773727
## 13   12    112       7        3 0.58069932 0.058812267 0.6516470 0.51747602
## 14   13    102       3        1 0.56361993 0.061285979 0.6355549 0.49982690
## 15   14     98       1        1 0.55786871 0.062138297 0.6301214 0.49390087
## 16   15     96       1        3 0.55205758 0.063014420 0.6246293 0.48791751
## 17   16     92       3        1 0.53405570 0.065857474 0.6076375 0.46938431
## 18   17     88       1        6 0.52798688 0.066841779 0.6018925 0.46315601
## 19   19     81       0        1 0.52798688 0.066841779 0.6018925 0.46315601
## 20   20     80       2        0 0.51478721 0.069197805 0.5895614 0.44949666
## 21   21     78       2        4 0.50158754 0.071594121 0.5771488 0.43591891
## 22   22     72       2        1 0.48765455 0.074313818 0.5641159 0.42155694
## 23   23     69       0        2 0.48765455 0.074313818 0.5641159 0.42155694
## 24   25     67       0        2 0.48765455 0.074313818 0.5641159 0.42155694
## 25   26     65       5        2 0.45014266 0.082489968 0.5291341 0.38294340
## 26   27     58       0        1 0.45014266 0.082489968 0.5291341 0.38294340
## 27   29     57       0        4 0.45014266 0.082489968 0.5291341 0.38294340
## 28   30     53       2        1 0.43315615 0.086859159 0.5135457 0.36535061
## 29   34     50       0        1 0.43315615 0.086859159 0.5135457 0.36535061
## 30   35     49       2        3 0.41547631 0.091722113 0.4973021 0.34711410
## 31   38     44       2        1 0.39659102 0.097443302 0.4800503 0.32764156
## 32   39     41       4        3 0.35789921 0.110145268 0.4441366 0.28840642
## 33   43     34       3        1 0.32631987 0.122385783 0.4147806 0.25672523
## 34   47     30       0        1 0.32631987 0.122385783 0.4147806 0.25672523
## 35   48     29       0        3 0.32631987 0.122385783 0.4147806 0.25672523
## 36   49     26       0        1 0.32631987 0.122385783 0.4147806 0.25672523
## 37   52     25       4        1 0.27410869 0.150324075 0.3680263 0.20415815
## 38   56     20       0        1 0.27410869 0.150324075 0.3680263 0.20415815
## 39   58     19       0        1 0.27410869 0.150324075 0.3680263 0.20415815
## 40   61     18       0        4 0.27410869 0.150324075 0.3680263 0.20415815
## 41   65     14       0        5 0.27410869 0.150324075 0.3680263 0.20415815
## 42   69      9       1        0 0.24365217 0.191013655 0.3542920 0.16756340
## 43   78      8       1        0 0.21319565 0.233116622 0.3366724 0.13500477
## 44   86      7       1        0 0.18273913 0.279558372 0.3160764 0.10565037
## 45  100      6       0        1 0.18273913 0.279558372 0.3160764 0.10565037
## 46  104      5       2        1 0.10964348 0.459876306 0.2700413 0.04451797
## 47  108      2       1        0 0.05482174 0.843496424 0.2863771 0.01049464
## 48  117      1       0        1 0.05482174 0.843496424 0.2863771 0.01049464
## 49    0    210       1        0 0.99523810 0.004773283 1.0000000 0.98597060
## 50    1    209      18        7 0.90952381 0.021764589 0.9491615 0.87154140
## 51    2    184      14        4 0.84032091 0.030352391 0.8918281 0.79178846
## 52    3    166       8        5 0.79982352 0.035018355 0.8566469 0.74676936
## 53    4    153       6        7 0.76845789 0.038640116 0.8289161 0.71240925
## 54    5    140       1        1 0.76296890 0.039299441 0.8240595 0.70640716
## 55    6    138       6        2 0.72979634 0.043287721 0.7944165 0.67043258
## 56    7    130       5        2 0.70172725 0.046706735 0.7689980 0.64034128
## 57    8    123      10        2 0.64467626 0.053860889 0.7164537 0.58008977
## 58    9    111       2        3 0.63306047 0.055374166 0.7056344 0.56795067
## 59   10    106       2        1 0.62111593 0.056988776 0.6945150 0.55547400
## 60   11    103       0        3 0.62111593 0.056988776 0.6945150 0.55547400
## 61   12    100       8        8 0.57142666 0.064166080 0.6480056 0.50389753
## 62   13     84       4        3 0.54421586 0.068647825 0.6225931 0.47570538
## 63   14     77       1        0 0.53714813 0.069881369 0.6159950 0.46839358
## 64   15     76       0        3 0.53714813 0.069881369 0.6159950 0.46839358
## 65   16     73       8        2 0.47828258 0.081051779 0.5606295 0.40803100
## 66   17     63       1        5 0.47069079 0.082616023 0.5534248 0.40032509
## 67   18     57       1        1 0.46243306 0.084490772 0.5457171 0.39185933
## 68   19     55       0        2 0.46243306 0.084490772 0.5457171 0.39185933
## 69   20     53       4        1 0.42753245 0.093160771 0.5131776 0.35618079
## 70   21     48       0        1 0.42753245 0.093160771 0.5131776 0.35618079
## 71   22     47       2        1 0.40933958 0.098104820 0.4961245 0.33773554
## 72   23     44       0        1 0.40933958 0.098104820 0.4961245 0.33773554
## 73   24     43       0        1 0.40933958 0.098104820 0.4961245 0.33773554
## 74   25     42       0        2 0.40933958 0.098104820 0.4961245 0.33773554
## 75   26     40       3        3 0.37863911 0.107942497 0.4678496 0.30643943
## 76   28     34       0        1 0.37863911 0.107942497 0.4678496 0.30643943
## 77   30     33       1        0 0.36716520 0.112243273 0.4575127 0.29465910
## 78   35     32       2        1 0.34421737 0.121168832 0.4364876 0.27145240
## 79   39     29       0        1 0.34421737 0.121168832 0.4364876 0.27145240
## 80   43     28       0        2 0.34421737 0.121168832 0.4364876 0.27145240
## 81   52     26       4        4 0.29126085 0.147223954 0.3886864 0.21825533
## 82   56     18       3        0 0.24271738 0.181069058 0.3461204 0.17020590
## 83   60     15       2        0 0.21035506 0.207466658 0.3158995 0.14007384
## 84   61     13       0        4 0.21035506 0.207466658 0.3158995 0.14007384
## 85   65      9       0        1 0.21035506 0.207466658 0.3158995 0.14007384
## 86  104      8       4        1 0.10517753 0.409929767 0.2348853 0.04709666
## 87  109      3       0        1 0.10517753 0.409929767 0.2348853 0.04709666
## 88  112      2       1        0 0.05258877 0.817338617 0.2609834 0.01059676
## 89  113      1       0        1 0.05258877 0.817338617 0.2609834 0.01059676
##        strata    sex
## 1    sex=male   male
## 2    sex=male   male
## 3    sex=male   male
## 4    sex=male   male
## 5    sex=male   male
## 6    sex=male   male
## 7    sex=male   male
## 8    sex=male   male
## 9    sex=male   male
## 10   sex=male   male
## 11   sex=male   male
## 12   sex=male   male
## 13   sex=male   male
## 14   sex=male   male
## 15   sex=male   male
## 16   sex=male   male
## 17   sex=male   male
## 18   sex=male   male
## 19   sex=male   male
## 20   sex=male   male
## 21   sex=male   male
## 22   sex=male   male
## 23   sex=male   male
## 24   sex=male   male
## 25   sex=male   male
## 26   sex=male   male
## 27   sex=male   male
## 28   sex=male   male
## 29   sex=male   male
## 30   sex=male   male
## 31   sex=male   male
## 32   sex=male   male
## 33   sex=male   male
## 34   sex=male   male
## 35   sex=male   male
## 36   sex=male   male
## 37   sex=male   male
## 38   sex=male   male
## 39   sex=male   male
## 40   sex=male   male
## 41   sex=male   male
## 42   sex=male   male
## 43   sex=male   male
## 44   sex=male   male
## 45   sex=male   male
## 46   sex=male   male
## 47   sex=male   male
## 48   sex=male   male
## 49 sex=female female
## 50 sex=female female
## 51 sex=female female
## 52 sex=female female
## 53 sex=female female
## 54 sex=female female
## 55 sex=female female
## 56 sex=female female
## 57 sex=female female
## 58 sex=female female
## 59 sex=female female
## 60 sex=female female
## 61 sex=female female
## 62 sex=female female
## 63 sex=female female
## 64 sex=female female
## 65 sex=female female
## 66 sex=female female
## 67 sex=female female
## 68 sex=female female
## 69 sex=female female
## 70 sex=female female
## 71 sex=female female
## 72 sex=female female
## 73 sex=female female
## 74 sex=female female
## 75 sex=female female
## 76 sex=female female
## 77 sex=female female
## 78 sex=female female
## 79 sex=female female
## 80 sex=female female
## 81 sex=female female
## 82 sex=female female
## 83 sex=female female
## 84 sex=female female
## 85 sex=female female
## 86 sex=female female
## 87 sex=female female
## 88 sex=female female
## 89 sex=female female</code></pre>
<pre class="r"><code>attr(surv_summary(sfit2), &quot;table&quot;)</code></pre>
<pre><code>## Warning in .get_data(x, data = data): The `data` argument is not provided. Data
## will be extracted from model fit.</code></pre>
<pre><code>##            records n.max n.start events   *rmean *se(rmean) median 0.95LCL
## sex=male       242   242     242    134 39.15475   3.430570     22      13
## sex=female     210   210     210    122 37.17683   3.660689     16      13
##            0.95UCL
## sex=male        35
## sex=female      22</code></pre>
<pre class="r"><code>plot(sfit2)</code></pre>
<p><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-7-1.png" width="672" />
More complete and complex plot function:</p>
<pre class="r"><code>ggsurvplot(sfit2, conf.int=TRUE, pval=TRUE, risk.table=TRUE, 
           legend.labs=c(&quot;male&quot;, &quot;female&quot;), legend.title=&quot;Sex&quot;,  
           palette=c(&quot;dodgerblue2&quot;, &quot;orchid2&quot;), 
           title=&quot;KM Curve for Job Duration Survival&quot;, 
           risk.table.height=.15)</code></pre>
<pre><code>## Warning: Vectorized input to `element_text()` is not officially supported.
## Results may be unexpected or may change in future versions of ggplot2.</code></pre>
<p><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<pre class="r"><code>ggsurvplot(
   sfit2,                     # survfit object with calculated statistics.
   pval = TRUE,             # show p-value of log-rank test.
   conf.int = TRUE,         # show confidence intervals for 
                            # point estimaes of survival curves.
   #conf.int.style = &quot;step&quot;,  # customize style of confidence intervals
   xlab = &quot;Time in weeks&quot;,   # customize X axis label.
   break.time.by = 5,     # break X axis in time intervals by 200.
   ggtheme = theme_light(), # customize plot and risk table with a theme.
   risk.table = &quot;abs_pct&quot;,  # absolute number and percentage at risk.
  risk.table.y.text.col = T,# colour risk table text annotations.
  risk.table.y.text = FALSE,# show bars instead of names in text annotations
                            # in legend of risk table.
  ncensor.plot = TRUE,      # plot the number of censored subjects at time t
  surv.median.line = &quot;hv&quot;,  # add the median survival pointer.
  legend.labs = 
    c(&quot;Male&quot;, &quot;Female&quot;),    # change legend labels.
  palette = 
    c(&quot;#E7B800&quot;, &quot;#2E9FDF&quot;) # custom color palettes.
)</code></pre>
<pre><code>## Warning: Vectorized input to `element_text()` is not officially supported.
## Results may be unexpected or may change in future versions of ggplot2.</code></pre>
<p><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-8-2.png" width="672" /></p>
</div>
<div id="cox-regression" class="section level2">
<h2>Cox Regression</h2>
<p>KM curves are good for visualizing differences in survival between two categorical groups, and the log-rank test for asking if there are differences in survival between different groups.</p>
<p>But this doesn’t generalize well for assessing the effect of quantitative variables.</p>
<p>At some point we may want to assess how multiple variables work together to influence survival.</p>
<p>For example, we may want to simultaneously examine the effect of sex and socioeconomic status, so as to adjust for factors like income, access to care, etc., before concluding that gender influences some outcome.</p>
<p>Cox PH regression can assess the effect of <strong>both categorical and continuous</strong> variables, and can model the effect of multiple variables at once.</p>
<p>The <code>coxph()</code> function uses the same syntax as <code>lm()</code>, <code>glm()</code>, etc.</p>
<p>The response variable (left hand-side) is the duration formated with <code>Surv()</code>. <code>~</code> separate left and right hand side in the formula. Explanatory variables go on the right side.</p>
<pre class="r"><code>Coxfit &lt;- coxph(Surv_time~sex, data=Unemployment)
Coxfit</code></pre>
<pre><code>## Call:
## coxph(formula = Surv_time ~ sex, data = Unemployment)
## 
##              coef exp(coef) se(coef)     z     p
## sexfemale 0.08562   1.08939  0.12551 0.682 0.495
## 
## Likelihood ratio test=0.46  on 1 df, p=0.4955
## n= 452, number of events= 256</code></pre>
<p>Interpretation:</p>
<p><strong>Statistical significance</strong>: <code>z</code> gives the Wald statistic value (<span class="math inline">\(z = \beta/\sigma(\beta)\)</span>). The wald statistic tests <span class="math inline">\(H_0: \beta = 0\)</span></p>
<p><strong>Regression coefficients</strong>:</p>
<ul>
<li>the <em>sign</em> of the regression <span class="math inline">\(\beta\)</span> give impact of the covariate on the hazard. A positive sign means that the hazard is higher. Thus the event is more likely, for subjects with higher values of that variable.</li>
<li><p><span class="math inline">\(\beta\)</span> gives the hazard ratio (HR) for the second group relative to the first group, that is, female versus male.</p></li>
<li><p><em>Hazard ratios</em> is given by <span class="math inline">\(exp(\beta\)</span>. It gives the effect size of covariates.</p></li>
</ul>
<blockquote>
<p>the multiplicative effect of that variable on the hazard rate (for each unit increase in that variable).</p>
</blockquote>
<p>So, for a categorical variable like gender, going from male (baseline) to female results in approximately 8.94 % change in hazard.</p>
<p>The rate of female is higher than the rate of male.</p>
<p>Remember:
&gt; <span class="math inline">\(HR=e^{\beta} =1\)</span>: No effect
&gt; <span class="math inline">\(HR=e^{\beta} &gt;1\)</span>: Increase in hazard
&gt; <span class="math inline">\(HR=e^{\beta} &lt;1\)</span>: Reduction in hazard</p>
<p><strong>Confidence intervals</strong> of the hazard ratios. The summary output also gives upper and lower 95% confidence intervals for the hazard ratio (<span class="math inline">\(exp(\beta)\)</span>).</p>
<p><strong>Global statistical significance</strong> of the model. Finally, p-values for three alternative tests for overall significance of the model are produced: likelihood-ratio test, Wald test, and score logrank statistics.</p>
<p>These three methods are asymptotically equivalent. For large enough N, they will give similar results. For small N, they may differ somewhat. The Likelihood ratio test has better behavior for small sample sizes, so it is generally preferred.</p>
<p>Notice that the p-value of the LR test is close to the p-value of the KM curve (which is the log-rank test). The two tests evaluate the difference in survival between gender group.</p>
<pre class="r"><code>summary(Coxfit)</code></pre>
<pre><code>## Call:
## coxph(formula = Surv_time ~ sex, data = Unemployment)
## 
##   n= 452, number of events= 256 
## 
##              coef exp(coef) se(coef)     z Pr(&gt;|z|)
## sexfemale 0.08562   1.08939  0.12551 0.682    0.495
## 
##           exp(coef) exp(-coef) lower .95 upper .95
## sexfemale     1.089     0.9179    0.8518     1.393
## 
## Concordance= 0.514  (se = 0.018 )
## Likelihood ratio test= 0.46  on 1 df,   p=0.5
## Wald test            = 0.47  on 1 df,   p=0.5
## Score (logrank) test = 0.47  on 1 df,   p=0.5</code></pre>
<pre class="r"><code># log-rank
survdiff(Surv_time~sex, data=Unemployment)</code></pre>
<pre><code>## Call:
## survdiff(formula = Surv_time ~ sex, data = Unemployment)
## 
##              N Observed Expected (O-E)^2/E (O-E)^2/V
## sex=male   242      134      139     0.182     0.426
## sex=female 210      122      117     0.216     0.426
## 
##  Chisq= 0.4  on 1 degrees of freedom, p= 0.5</code></pre>
<pre class="r"><code># Wilcoxon
survdiff(Surv_time~sex, data=Unemployment, rho = 1)</code></pre>
<pre><code>## Call:
## survdiff(formula = Surv_time ~ sex, data = Unemployment, rho = 1)
## 
##              N Observed Expected (O-E)^2/E (O-E)^2/V
## sex=male   242     91.9     96.1     0.185     0.563
## sex=female 210     84.5     80.3     0.221     0.563
## 
##  Chisq= 0.6  on 1 degrees of freedom, p= 0.5</code></pre>
<pre class="r"><code># log-rank
survdiff(Surv_time~sex + race, data=Unemployment)</code></pre>
<pre><code>## Call:
## survdiff(formula = Surv_time ~ sex + race, data = Unemployment)
## 
##                             N Observed Expected (O-E)^2/E (O-E)^2/V
## sex=male, race=nonwhite    56       31     31.2   0.00158   0.00192
## sex=male, race=white      186      103    107.8   0.21454   0.39494
## sex=female, race=nonwhite  61       34     37.0   0.24162   0.30249
## sex=female, race=white    149       88     80.0   0.80447   1.25291
## 
##  Chisq= 1.4  on 3 degrees of freedom, p= 0.7</code></pre>
</div>
<div id="cox-model-with-multiple-covariates" class="section level2">
<h2>Cox model with multiple covariates</h2>
<p>For the sake of the exercise, let add a quantitative variables like <code>age</code></p>
<pre class="r"><code>Unemployment$age &lt;- abs(rnorm(length(Unemployment$duration), 35 , 20))
Coxfit2 &lt;- coxph(Surv_time~sex + race + search + pubemp + age, data=Unemployment)
summary(Coxfit2)</code></pre>
<pre><code>## Call:
## coxph(formula = Surv_time ~ sex + race + search + pubemp + age, 
##     data = Unemployment)
## 
##   n= 452, number of events= 256 
## 
##                 coef  exp(coef)   se(coef)      z Pr(&gt;|z|)   
## sexfemale  0.0392404  1.0400205  0.1283678  0.306  0.75984   
## racewhite  0.0384013  1.0391481  0.1453514  0.264  0.79163   
## searchyes  0.2388795  1.2698255  0.1323358  1.805  0.07106 . 
## pubempyes -0.5147452  0.5976529  0.1655592 -3.109  0.00188 **
## age       -0.0002203  0.9997797  0.0034132 -0.065  0.94853   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##           exp(coef) exp(-coef) lower .95 upper .95
## sexfemale    1.0400     0.9615    0.8087    1.3375
## racewhite    1.0391     0.9623    0.7815    1.3817
## searchyes    1.2698     0.7875    0.9797    1.6458
## pubempyes    0.5977     1.6732    0.4320    0.8267
## age          0.9998     1.0002    0.9931    1.0065
## 
## Concordance= 0.561  (se = 0.019 )
## Likelihood ratio test= 13.99  on 5 df,   p=0.02
## Wald test            = 13.03  on 5 df,   p=0.02
## Score (logrank) test = 13.24  on 5 df,   p=0.02</code></pre>
<p>The p-value for all three overall tests (likelihood, Wald, and score) are significant, indicating that the model is significant.</p>
<p>The three tests (likelihood, Wald, and score tests) evaluate the omnibus null hypothesis that all of the <span class="math inline">\(\beta\)</span> are 0 simultaneously.</p>
<p>In the above example, the test statistics are in close agreement, and the omnibus null hypothesis is soundly rejected.</p>
<p>In the multivariate Cox analysis, the covariates sex and ph.ecog remain significant (p &lt; 0.05). However, the covariate age fails to be significant (p = 0.23, which is grater than 0.05).</p>
<p>The p-value for <code>pubempyes</code> is , with a hazard ratio HR = 0.5976529 indicating a strong relationship between the public private status and return to employment.</p>
<p>The hazard ratios of covariates are interpretable as multiplicative effects on the hazard. For example, holding the other covariates constant, being public status reduces the hazard by a factor of = 0.5976529 , or -58.7652872 %. We conclude that, being public employee is associated with longer unemployment period.</p>
<p>By contrast, the p-value for <code>searchyes</code> covariates is now 0.0710588. The hazard ratio HR = 1.2698255. Holding the other covariates constant, an effective search induces weekly hazard of finding a job by a factor of 1.2698255, or `26.98254841%, which is a significant contribution.</p>
<div id="visualizing-the-estimated-distribution-of-survival-times" class="section level3">
<h3>Visualizing the estimated distribution of survival times</h3>
<p><strong>Plot the baseline survival function</strong></p>
<p>Having fit a Cox model to the data, it’s possible to visualize the predicted survival proportion at any given point in time for a particular risk group. The function survfit() estimates the survival proportion, by default at the mean values of covariates.</p>
<pre class="r"><code>plot(survfit(Coxfit2))

fit &lt;- survfit(Coxfit2,  data = Unemployment)
ggsurvplot(fit, conf.int = TRUE, palette = &quot;Dark2&quot;, 
           censor = FALSE, surv.median.line = &quot;hv&quot;)</code></pre>
<p><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-12-1.png" width="672" /><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-12-2.png" width="672" /></p>
</div>
<div id="continuing-with-categorical-age" class="section level3">
<h3>Continuing with categorical <code>age</code></h3>
<p>Finally, let’s try creating a categorical variable on <code>age</code>: upper or lower to the average age</p>
<pre class="r"><code>hist(Unemployment$age)</code></pre>
<p><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<pre class="r"><code>ggplot(Unemployment, aes(age)) + geom_histogram(bins=20)</code></pre>
<p><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-13-2.png" width="672" /></p>
<pre class="r"><code>Unemployment$cl_age &lt;-  cut(Unemployment$age, breaks=c(0, mean(Unemployment$age), Inf), labels=c(&quot;young&quot;, &quot;old&quot;))

ggsurvplot(survfit(Surv_time~cl_age, data=Unemployment), pval=TRUE)</code></pre>
<p><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-13-3.png" width="672" /></p>
<p>The <code>survminer</code> package determines the optimal cutpoint for one or multiple continuous variables at once, using the maximally selected rank statistics from the <code>maxstat</code> R package.</p>
<pre class="r"><code>res.cut &lt;- surv_cutpoint(Unemployment, time = &quot;duration&quot;, event = &quot;spell&quot;,    variables = c(&quot;age&quot;))
summary(res.cut)</code></pre>
<pre><code>##     cutpoint statistic
## age 19.64392  1.530619</code></pre>
<pre class="r"><code># 2. Plot cutpoint for DEPDC1
# palette = &quot;npg&quot; (nature publishing group), see ?ggpubr::ggpar
plot(res.cut, &quot;age&quot;, palette = &quot;npg&quot;)</code></pre>
<pre><code>## $age</code></pre>
<p><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>Categorize the variable</p>
<pre class="r"><code>res.cat &lt;- surv_categorize(res.cut)
head(res.cat)</code></pre>
<pre><code>##   duration spell  age
## 1        4     1 high
## 2        7     0 high
## 3        1     0  low
## 4        1     1 high
## 5        3     1 high
## 6        1     1  low</code></pre>
<p>Fit survival curves and visualize</p>
<pre class="r"><code>sfit3 &lt;- survfit(Surv_time ~age, data = res.cat)
ggsurvplot(sfit3, risk.table = TRUE, conf.int = TRUE)</code></pre>
<pre><code>## Warning: Vectorized input to `element_text()` is not officially supported.
## Results may be unexpected or may change in future versions of ggplot2.</code></pre>
<p><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>Facet the output crossing categorical covariates</p>
<pre class="r"><code>sfit4 &lt;- survfit( Surv_time ~ sex + pubemp + race,
                data = Unemployment )

ggsurv &lt;- ggsurvplot(sfit4, fun = &quot;event&quot;, conf.int = TRUE,
  risk.table = TRUE, risk.table.col=&quot;strata&quot;, 
  ggtheme = theme_bw())</code></pre>
<pre><code>## Warning: Vectorized input to `element_text()` is not officially supported.
## Results may be unexpected or may change in future versions of ggplot2.</code></pre>
<pre class="r"><code>ggsurv</code></pre>
<p><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<pre class="r"><code>curv_facet &lt;- ggsurv$plot + facet_grid(race~sex)
curv_facet</code></pre>
<p><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>Facetting risk tables: Generate risk table for each facet plot item</p>
<pre class="r"><code>ggsurv$table + facet_grid(race ~sex, scales = &quot;free&quot;)+
 theme(legend.position = &quot;none&quot;)</code></pre>
<p><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>(New in survminer 0.2.4: the survminer package can now determine the optimal cutpoint for one or multiple continuous variables at once, using the surv_cutpoint() and surv_categorize() functions. Refer to this blog post for more information.)
TCGA</p>
<p>Remember, the Cox regression analyzes the continuous variable over the whole range of its distribution, where the log-rank test on the Kaplan-Meier plot can change depending on how you categorize your continuous variable. They’re answering a similar question in a different way: the regression model is asking, “what is the effect of age on survival?”, while the log-rank test and the KM plot is asking, “are there differences in survival between those less than 70 and those greater than 70 years old?”.</p>
</div>
</div>
<div id="random-forests-model" class="section level2">
<h2>Random Forests Model</h2>
<p>As a final example of what some might perceive as a data-science-like way to do time-to-event modeling, I’ll use the ranger() function to fit a Random Forests Ensemble model to the data.</p>
<p><code>ranger()</code> builds a model for each observation in the data set. The next block of code builds the model using the same variables used in the Cox model above, and plots twenty random curves, along with a curve that represents the global average for all of the patients. Note that I am using plain old base R graphics here.</p>
<pre class="r"><code>library(ranger)</code></pre>
<pre><code>## Warning: le package &#39;ranger&#39; a été compilé avec la version R 3.6.3</code></pre>
<pre class="r"><code># ranger model
r_fit &lt;- ranger(Surv_time ~ sex + race + search +  pubemp + age,
                     data = Unemployment,
                     mtry = 4,
                     importance = &quot;permutation&quot;,
                     splitrule = &quot;extratrees&quot;,
                     verbose = TRUE)

# Average the survival models
death_times &lt;- r_fit$unique.death.times 
surv_prob &lt;- data.frame(r_fit$survival)
avg_prob &lt;- sapply(surv_prob,mean)

# Plot the survival models for each patient
plot(r_fit$unique.death.times,r_fit$survival[1,], 
     type = &quot;l&quot;, 
     ylim = c(0,1),
     col = &quot;red&quot;,
     xlab = &quot;Days&quot;,
     ylab = &quot;survival&quot;,
     main = &quot;Jobseeker Survival Curves&quot;)

#
cols &lt;- colors()
for (n in sample(c(2:dim(Unemployment)[1]), 20)){
  lines(r_fit$unique.death.times, r_fit$survival[n,], type = &quot;l&quot;, col = cols[n])
}
lines(death_times, avg_prob, lwd = 2)
legend((range(Unemployment$duration)[2]-range(Unemployment$duration)[1])/2, 0.8, legend = c(&#39;Average = black&#39;))</code></pre>
<p><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>Ranks of variable importance</p>
<pre class="r"><code>vi &lt;- data.frame(sort(round(r_fit$variable.importance, 4), decreasing = TRUE))
names(vi) &lt;- &quot;importance&quot;
head(vi)</code></pre>
<pre><code>##        importance
## pubemp     0.0344
## sex        0.0183
## age        0.0056
## search     0.0028
## race      -0.0006</code></pre>
<p>Finally, ploting the three baseloine survival curves (KM, Cox, RF)</p>
<pre class="r"><code># Time, survival prob and model label for KM
kmi &lt;- rep(&quot;KM&quot;,length(sfit1$time))
km_df &lt;- data.frame(sfit1$time,sfit1$surv,kmi)
names(km_df) &lt;- c(&quot;Time&quot;,&quot;Surv&quot;,&quot;Model&quot;)
# Time, survival prob and model label for COX
bh &lt;- basehaz(Coxfit)
bs &lt;- exp(-bh[,1])^(exp(Coxfit$coef))
coxi &lt;- rep(&quot;Cox&quot;,length(bh[,2]))
cox_df &lt;- data.frame(bh[,2],bs, coxi)
names(cox_df) &lt;- c(&quot;Time&quot;,&quot;Surv&quot;,&quot;Model&quot;)
# Time, survival prob and model label for RF
rfi &lt;- rep(&quot;RF&quot;,length(r_fit$unique.death.times))
rf_df &lt;- data.frame(r_fit$unique.death.times,avg_prob,rfi)
names(rf_df) &lt;- c(&quot;Time&quot;,&quot;Surv&quot;,&quot;Model&quot;)

plot_df &lt;- rbind(km_df,cox_df,rf_df)

p &lt;- ggplot(plot_df, aes(x = Time, y = Surv, color = Model))
p + geom_line()</code></pre>
<p><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
</div>
<div id="diagnostic-of-cox-ph-model" class="section level2">
<h2>Diagnostic of Cox PH model</h2>
<ol style="list-style-type: decimal">
<li>Testing the proportional hazards assumption.</li>
<li>Examining influential observations (or outliers).</li>
<li>Detecting nonlinearity in relationship between the log hazard and the covariates.</li>
</ol>
<p>In order to check these model assumptions, Residuals method are used. The common residuals for the Cox model include:</p>
<ul>
<li>Schoenfeld residuals to check the proportional hazards assumption</li>
<li>Martingale residual to assess nonlinearity</li>
<li>Deviance residual (symmetric transformation of the Martinguale residuals), to examine influential observations</li>
</ul>
<div id="testing-proportional-hazards-assumption" class="section level3">
<h3>Testing proportional Hazards assumption</h3>
<p>The PH assumption can be checked using statistical tests and graphical diagnostics based on the scaled Schoenfeld residuals.</p>
<p>In principle, the Schoenfeld residuals are independent of time. A plot that shows a non-random pattern against time is evidence of violation of the PH assumption.</p>
<p>The function <code>cox.zph()</code> provides a convenient solution to test the proportional hazards assumption for each covariate included in a Cox model.</p>
<p>For each covariate, correlation between the corresponding set of scaled Schoenfeld residuals with time is calculated to test for independence between residuals and time.</p>
<p>Additionally, it performs a global test for the model as a whole.</p>
<p>The proportional hazard assumption is supported by a non-significant relationship between residuals and time, and refuted by a significant relationship.</p>
<pre class="r"><code>test.ph &lt;- cox.zph(Coxfit)
test.ph</code></pre>
<pre><code>##        chisq df   p
## sex    0.151  1 0.7
## GLOBAL 0.151  1 0.7</code></pre>
<pre class="r"><code>ggcoxzph(test.ph)</code></pre>
<p><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<pre class="r"><code>test.ph &lt;- cox.zph(Coxfit2)
test.ph</code></pre>
<pre><code>##        chisq df     p
## sex    0.324  1 0.569
## race   1.850  1 0.174
## search 3.318  1 0.069
## pubemp 2.554  1 0.110
## age    0.829  1 0.363
## GLOBAL 8.250  5 0.143</code></pre>
<pre class="r"><code>ggcoxzph(test.ph)</code></pre>
<p><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-24-2.png" width="672" />
In the figure above, the solid line is a smoothing spline fit to the plot, with the dashed lines representing a <span class="math inline">\(\pm 2 \sigma\)</span> band around the fit.</p>
<p>Systematic departures from a horizontal line are indicative of <strong>non-proportional</strong> hazards, since proportional hazards assumes that estimates <span class="math inline">\(\beta_1, \beta_2,\dots \beta_k\)</span> do not vary much over time.</p>
<p>Another graphical methods for checking proportional hazards is to plot <span class="math inline">\(\ln (-\ln (S(t)))\)</span> vs. <span class="math inline">\(t\)</span> or <span class="math inline">\(\ln(t)\)</span> and look for parallelism. This can be done only for categorical covariates.</p>
<p>A violations of proportional hazards assumption can be resolved by:</p>
<ul>
<li>Adding covariate*time interaction</li>
<li>Stratification</li>
</ul>
</div>
<div id="testing-influential-observations" class="section level3">
<h3>Testing influential observations</h3>
<p>Influential observotation can be visualized with the <em>deviance residuals</em> or the <em>dfbeta values</em>.</p>
<p><code>ggcoxdiagnostics()</code> permits residuals diagnostic and visualisation</p>
<p>argument <code>type</code> precises the type of residuals to present on Y axis (<code>c(“martingale”, “deviance”, “score”, “schoenfeld”, “dfbeta”, “dfbetas”, “scaledsch”, “partial”)</code>.</p>
<p><code>linear.predictions</code>: a logical value <code>TRUE</code> to show linear predictions for observations or <code>FALSE</code> just indexed of observations on X axis.</p>
<p><code>dfbeta</code> estimates changes in the regression coefficients upon deleting each observation in turn;</p>
<p><code>dfbetas</code> produces the estimated changes in the coefficients divided by their standard errors.</p>
<pre class="r"><code>ggcoxdiagnostics(Coxfit2, type = &quot;dfbetas&quot;,
                 linear.predictions = FALSE, ggtheme = theme_bw())</code></pre>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<p>To check outliers: The deviance residual is a normalized transform of the martingale residual.</p>
<p>These residuals should be roughtly symmetrically distributed about zero with a standard deviation of 1.</p>
<p>Positive values correspond to events that “occur too soon” compared to expected survival times.</p>
<p>Negative values correspond to states that “are longer”.</p>
<p>Very large or small values are outliers, which are poorly predicted by the model.</p>
<pre class="r"><code>ggcoxdiagnostics(Coxfit2, type = &quot;deviance&quot;,
                 linear.predictions = FALSE, ggtheme = theme_bw())</code></pre>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
</div>
<div id="testing-non-linearity-of-covariates-effects" class="section level3">
<h3>Testing non linearity of covariates effects</h3>
<p>We asses linear functional form between duration and covariates with Martingale residuals and partial residuals.</p>
<p>Martingale residuals may present any value in the range <span class="math inline">\((\infty, +1)\)</span>:</p>
<p>A value of martinguale residuals near 1 represents events that occur too soon and large negative values correspond to state lasting too long.</p>
<p>Graphs of continuous covariates against martingale residuals help to choose the functional form, which is suggested by the approximated line on residuals</p>
<p>Low increase tendancy reveals a functional form like logarithme or square root. Fast increase correspond to power transformation.</p>
<pre class="r"><code>ggcoxfunctional(Surv(duration, spell) ~ age + log(age) + sqrt(age), data = Unemployment)</code></pre>
<pre><code>## Warning: arguments formula is deprecated; will be removed in the next version;
## please use fit instead.</code></pre>
<p><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
</div>
</div>
<div id="parametric-model---aft" class="section level2">
<h2>Parametric model - AFT</h2>
<p>An accelerated failure-time (AFT) model is a parametric model with covariates and failure times following the survival function of the form <span class="math inline">\(S(x_{jZ}) = S_0 (x \cdot exp \{\theta&#39;Z\})\)</span>, where <span class="math inline">\(S_0\)</span> is a function for the baseline survival rate. The term <span class="math inline">\(exp \{\theta&#39;Z\})\)</span> is called the <em>acceleration factor</em>.</p>
<p>The AFT model uses covariates to place individuals on different time scales - scaling by the covariates in <span class="math inline">\(S(t_{jZ})\)</span> via <span class="math inline">\(exp \{\theta&#39;Z\})\)</span>.</p>
<p>The AFT model can be rewritten in a log-linear form, where the log of
failure time is linearly related to the mean <span class="math inline">\(\mu\)</span> (the acceleration factor), and an error term <span class="math inline">\(\sigma W\)</span>:
<span class="math display">\[ln t = \mu - \theta&#39; Z + \sigma \epsilon\]</span></p>
<p><span class="math inline">\(\epsilon\)</span> describes the error distribution. The following models for <span class="math inline">\(\epsilon\)</span> are implemented in R <code>survival</code> :</p>
<table>
<thead>
<tr class="header">
<th>Distribution</th>
<th>df</th>
<th align="center">Included in survival?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>exponential</td>
<td>1</td>
<td align="center">yes</td>
</tr>
<tr class="even">
<td>Weibull</td>
<td>2</td>
<td align="center">yes</td>
</tr>
<tr class="odd">
<td>lognormal</td>
<td>2</td>
<td align="center">yes</td>
</tr>
<tr class="even">
<td>log logistic</td>
<td>2</td>
<td align="center">yes</td>
</tr>
<tr class="odd">
<td>generalized gamma</td>
<td>3</td>
<td align="center">no</td>
</tr>
</tbody>
</table>
<p>The <code>survreg()</code> function from the <code>survival</code> package is used for AFT modeling.</p>
<p>The 1rst argument is <code>formula</code>, where a survival object is regressed on predictors.</p>
<p>The argument <code>dist</code> has several options to describe the parametric model used <code>("weibull", "exponential", "gaussian", "logistic", "lognormal", or "loglogistic")</code>.</p>
<pre class="r"><code># srFit &lt;- survreg(Surv(duration, spell) ~ sex + race, dist=&quot;weibull&quot;, data=Unemployment)
# Error, likely choking on the zeros.
Surv_time2 &lt;- with( Unemployment, Surv(duration+1, spell))# weeks starts with one.
Model0 &lt;-  survreg(Surv_time2~sex,dist=&#39;weibull&#39;, data=Unemployment)
summary(Model0)</code></pre>
<pre><code>## 
## Call:
## survreg(formula = Surv_time2 ~ sex, data = Unemployment, dist = &quot;weibull&quot;)
##               Value Std. Error     z       p
## (Intercept)  3.6199     0.1019 35.53 &lt; 2e-16
## sexfemale   -0.1335     0.1467 -0.91 0.36273
## Log(scale)   0.1584     0.0478  3.31 0.00093
## 
## Scale= 1.17 
## 
## Weibull distribution
## Loglik(model)= -1155.7   Loglik(intercept only)= -1156.1
##  Chisq= 0.83 on 1 degrees of freedom, p= 0.36 
## Number of Newton-Raphson Iterations: 5 
## n= 452</code></pre>
<p>When <span class="math inline">\(\sigma = 1\)</span>, the Weibull model is equivalent to the exponential model. We consider two strategies
for choosing the final model:</p>
<ul>
<li>a likelihood ratio test, which evaluates the null hypothesis <span class="math inline">\(\sigma = 1\)</span> against the two-sided
alternative, and</li>
<li>examination of the significance of the Log(scale) coefficient (see the output to summary(srFit)).</li>
</ul>
<p>In the example, both approaches result in the same conclusion: there is insuficient evidence to
reject the hypothesis that <span class="math inline">\(\sigma = 1\)</span> (H0). For this reason, we would likely go with the simpler
exponential model.</p>
</div>
<div id="weibull-model" class="section level2">
<h2>Weibull Model</h2>
<pre class="r"><code>library( SurvRegCensCov)</code></pre>
<pre><code>## Warning: le package &#39;SurvRegCensCov&#39; a été compilé avec la version R 3.6.3</code></pre>
<pre><code>## Registered S3 method overwritten by &#39;SurvRegCensCov&#39;:
##   method    from 
##   print.src dplyr</code></pre>
<pre class="r"><code>WeibullReg(Surv_time2 ~ sex, data=Unemployment)</code></pre>
<pre><code>## $formula
## Surv_time2 ~ sex
## 
## $coef
##             Estimate          SE
## lambda    0.04551665 0.007404146
## gamma     0.85353226 0.040819167
## sexfemale 0.11395918 0.125144711
## 
## $HR
##                 HR        LB       UB
## sexfemale 1.120706 0.8769372 1.432238
## 
## $ETR
##                 ETR        LB       UB
## sexfemale 0.8750145 0.6563751 1.166483
## 
## $summary
## 
## Call:
## survival::survreg(formula = formula, data = data, dist = &quot;weibull&quot;)
##               Value Std. Error     z       p
## (Intercept)  3.6199     0.1019 35.53 &lt; 2e-16
## sexfemale   -0.1335     0.1467 -0.91 0.36273
## Log(scale)   0.1584     0.0478  3.31 0.00093
## 
## Scale= 1.17 
## 
## Weibull distribution
## Loglik(model)= -1155.7   Loglik(intercept only)= -1156.1
##  Chisq= 0.83 on 1 degrees of freedom, p= 0.36 
## Number of Newton-Raphson Iterations: 5 
## n= 452</code></pre>
<div id="adequacy-of-weibull-model" class="section level3">
<h3>Adequacy of Weibull model</h3>
<p>Weibull model with categorical variables can be checked for its adequacy by stratified Kaplan-Meier curves.</p>
<p>A plot of log survival time versus <span class="math inline">\(log[–log(KM)]\)</span> will show linear and parallel lines if the model is adequate : Weibull regression diagnostic plot showing that the lines for male and female are generally parallel and linear in its scale.</p>
<pre class="r"><code>WeibullDiag(Surv_time2 ~ sex, data=Unemployment)</code></pre>
<p><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
</div>
</div>
<div id="weibull-version-2" class="section level2">
<h2>Weibull version 2</h2>
<p>With <code>eha</code>package</p>
<p>The coefficient of covariates in the above output is the HR in log scale. Thus, the exponentiation of coefficient gives the HR.</p>
<p>Hazard, cumulative hazard, density and survivor functions can be plotted from the output of a Weibull regression model.</p>
<p>graphical display of the output of Weibull regression model. The fn argument specifies the functions to be plotted. It receives a vector of string values, choosing from “haz”, “cum”, “den” and “sur”. The newdata argument specifies covariate values at which to plot the function. If covariates are left unspecified, the default value is the mean of the covariate in the training dataset. In the example, four plots were drawn at age of 80, 60, 40 and 20 years old (in the order from left to right and from top to bottom). The sex and ph.ecog variables were set at values of 2 and 3, respectively.</p>
<pre class="r"><code>library(eha)</code></pre>
<pre><code>## Warning: le package &#39;eha&#39; a été compilé avec la version R 3.6.3</code></pre>
<pre class="r"><code>Weib1 &lt;- weibreg(Surv_time2 ~ sex + age, data=Unemployment)
summary(Weib1)</code></pre>
<pre><code>## Call:
## weibreg(formula = Surv_time2 ~ sex + age, data = Unemployment)
## 
## Covariate           Mean       Coef Exp(Coef)  se(Coef)    Wald p
## sex 
##             male    0.553     0         1           (reference)
##           female    0.447     0.111     1.118     0.125     0.374 
## age                34.175     0.001     1.001     0.003     0.767 
## 
## log(scale)                    3.659    38.835     0.168     0.000 
## log(shape)                   -0.158     0.854     0.048     0.001 
## 
## Events                    256 
## Total time at risk          8819 
## Max. log. likelihood      -1155.7 
## LR test statistic         0.92 
## Degrees of freedom        2 
## Overall p-value           0.63266</code></pre>
<pre class="r"><code>par(mfrow=c(2,2))
plot(Weib1 , fn=&quot;sur&quot;, new.data = c(0, 40))</code></pre>
<p><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
<div id="graphical-goodness-of-fit-test" class="section level3">
<h3>Graphical goodness-of-fit test</h3>
<p>The eha package has a function check.dist() to test the goodness-of-fit by graphical visualization. It compares the cumulative hazards functions for non-parametric and parametric model, requiring objects of “coxreg” and “phreg” as the first and second argument.</p>
<pre class="r"><code>phreg1 &lt;- phreg(Surv_time2 ~ sex + age, data=Unemployment, dist = &#39;weibull&#39;)
summary(phreg1)</code></pre>
<pre><code>## Call:
## phreg(formula = Surv_time2 ~ sex + age, data = Unemployment, 
##     dist = &quot;weibull&quot;)
## 
## Covariate          W.mean      Coef Exp(Coef)  se(Coef)    Wald p
## sex 
##             male    0.553     0         1           (reference)
##           female    0.447     0.111     1.118     0.125     0.374 
## age                34.175     0.001     1.001     0.003     0.767 
## 
## log(scale)                    3.659               0.168     0.000 
## log(shape)                   -0.158               0.048     0.001 
## 
## Events                    256 
## Total time at risk          8819 
## Max. log. likelihood      -1155.7 
## LR test statistic         0.92 
## Degrees of freedom        2 
## Overall p-value           0.632855</code></pre>
<pre class="r"><code>coxreg1 &lt;- coxreg(Surv_time2 ~ sex + age, data=Unemployment)
summary(coxreg1)</code></pre>
<pre><code>## Call:
## coxreg(formula = Surv_time2 ~ sex + age, data = Unemployment)
## 
## Covariate           Mean       Coef     Rel.Risk   S.E.    Wald p
## sex 
##             male    0.553     0         1 (reference)
##           female    0.447     0.085     1.088     0.126     0.501 
## age                34.175     0.001     1.001     0.003     0.882 
## 
## Events                    256 
## Total time at risk          8819 
## Max. log. likelihood      -1353.1 
## LR test statistic         0.49 
## Degrees of freedom        2 
## Overall p-value           0.784074</code></pre>
<pre class="r"><code>check.dist(phreg1, coxreg1)</code></pre>
<p><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<p>The solid line is the parametric Weibull cumulative hazard function and the dashed line is non-parametric function.</p>
<p>It appears that the parametric function fits well to the semi-parametric function (Figure 3). Note that non-parametric model is closer to the observed data because no function is assumed for the baseline hazard function.</p>
<p><a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5233524/" class="uri">https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5233524/</a></p>
</div>
<div id="variable-selection-and-model-development" class="section level3">
<h3>Variable selection and model development</h3>
<p>Like generalized linear model development (4), it is essential to include statistically important and clinically relevant covariates into the model in fitting parametric regression model. While clinical relevance is judged by clinical expertise, the statistical importance is determined by software. The anova() function tests the statistical importance of a covariate, interaction and non-linear terms. The function reports Chi-square statistics and associated P value. Also, it provides dot charts depicting the importance of variables in the model.</p>
<pre class="r"><code>library(rms)</code></pre>
<pre><code>## Warning: le package &#39;rms&#39; a été compilé avec la version R 3.6.3</code></pre>
<pre><code>## Le chargement a nécessité le package : Hmisc</code></pre>
<pre><code>## Warning: le package &#39;Hmisc&#39; a été compilé avec la version R 3.6.3</code></pre>
<pre><code>## Le chargement a nécessité le package : lattice</code></pre>
<pre><code>## Warning: le package &#39;lattice&#39; a été compilé avec la version R 3.6.3</code></pre>
<pre><code>## Le chargement a nécessité le package : Formula</code></pre>
<pre><code>## 
## Attachement du package : &#39;Hmisc&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:dplyr&#39;:
## 
##     src, summarize</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     format.pval, units</code></pre>
<pre><code>## Le chargement a nécessité le package : SparseM</code></pre>
<pre><code>## Warning: le package &#39;SparseM&#39; a été compilé avec la version R 3.6.2</code></pre>
<pre><code>## 
## Attachement du package : &#39;SparseM&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:base&#39;:
## 
##     backsolve</code></pre>
<pre class="r"><code>Weib2 &lt;- psm(Surv_time2 ~ sex + race + age  + pubemp, dist=&quot;weibull&quot;, data=Unemployment)
anova(Weib2)</code></pre>
<pre><code>##                 Wald Statistics          Response: Surv_time2 
## 
##  Factor     Chi-Square d.f. P     
##  sex         0.12      1    0.7281
##  race        0.08      1    0.7807
##  age         0.05      1    0.8258
##  pubemp     10.45      1    0.0012
##  TOTAL      11.40      4    0.0224</code></pre>
<pre class="r"><code>plot(anova(Weib2) , margin = c(&quot;chisq&quot;, &quot;d.f.&quot;, &quot;P&quot;))</code></pre>
<p><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
<p>In the example, we included all available covariates into the model to rank their statistical importance. This is often the case in real research setting that researchers have no prior knowledge on which variable should be included. The first argument of psm() function is a formula describing the response variable and covariates, as well as interaction between predictors. The output of anova() includes variable names, Chi-square statistics, degree of freedom and p-value. Dot chart is drawn with generic function plot(). It appears that meal.cal is the least important variable and ph.ecog is the most important one (Figure 4). Some pre-specified rules can be applied to inclusion/exclusion of variables (4).</p>
<p>Alternatively, model development can be done with backward elimination on covariates. This method starts with a full model that included all available covariates and then applies Wald test to examine the relative importance of each one. Statistical significance level for a covariate to stay in a model can be specified. R provides a function fastbw() to perform fast backward variable selection.</p>
<p>An external file that holds a picture, illustration, etc. Object name is atm-04-24-484-fig9.jpg</p>
<pre class="r"><code>fastbw(Weib2, rule=&quot;aic&quot;)</code></pre>
<pre><code>## 
##  Deleted Chi-Sq d.f. P      Residual d.f. P      AIC  
##  age     0.05   1    0.8258 0.05     1    0.8258 -1.95
##  race    0.08   1    0.7712 0.13     2    0.9357 -3.87
##  sex     0.11   1    0.7380 0.24     3    0.9700 -5.76
## 
## Approximate Estimates after Deleting Factors
## 
##               Coef   S.E. Wald Z         P
## (Intercept) 3.4132 0.0799  42.72 0.0000000
## pubemp=yes  0.6297 0.1885   3.34 0.0008379
## 
## Factors in Final Model
## 
## [1] pubemp</code></pre>
<p>The first argument of fastbw() receives an object fit by psm(). The rule argument defines stopping rule for backward elimination. The default is Akaike’s information criterion (AIC). If P value is used as the stopping rule (rule=“p”), the significance level for staying in a model can be modified using sls argument (sls =0.1 for example). The output shows that variables meal.cal, sex, pat.karno and wt.loss are eliminated from the model based on AIC. Sometimes if you want to retain a covariate in the model based on clinical judgment, the force argument can be employed. It passes a vector of integers specifying covariates to be retained in the model. Intercept is not counted.</p>
<p>Weibull model can be used to predict outcomes of new subjects, allowing predictors to vary. In Weibull regression model, the outcome is median survival time for a given combination of covariates. We first use Predict() to calculate median survival time in log scale, then use ggplot() function to draw plots.</p>
<p>An external file that holds a picture, illustration, etc. Object name is atm-04-24-484-fig10.jpg</p>
<pre class="r"><code>#########################################</code></pre>
</div>
</div>
</div>
<div id="exercise-inspired-from-allison2010" class="section level1">
<h1>Exercise inspired from <span class="citation">Allison (<a href="#ref-Allison2010">2010</a>)</span></h1>
<p>The exercise analyses the job duration <code>jobdur.txt</code>. The data consist of 100 job durations, measured from the year to entry into hte job until the year that the employee quit.</p>
<p>Duration after the fifth year are censored. If the employee is fired, the job duration is censored at the end of its last full year.</p>
<p>Survival times have values of <code>1, 2, 3, 4 or 5</code></p>
<div id="import-data-summary-statistics" class="section level2">
<h2>Import data &amp; Summary statistics</h2>
<pre class="r"><code>jobdur &lt;- read.table(&quot;./data/jobdur.txt&quot;, header = TRUE)
head(jobdur)</code></pre>
<pre><code>##   dur event ed prestige salary
## 1   1     1  7        3     19
## 2   4     1 14       62     17
## 3   5     0 16       70     18
## 4   2     1 12       43    135
## 5   3     1  9       18     12
## 6   1     1 11       31     12</code></pre>
<pre class="r"><code>summary(jobdur)</code></pre>
<pre><code>##       dur           event            ed           prestige     
##  Min.   :1.00   Min.   :0.00   Min.   : 6.00   Min.   :  1.00  
##  1st Qu.:1.00   1st Qu.:1.00   1st Qu.:10.00   1st Qu.: 26.75  
##  Median :2.50   Median :1.00   Median :12.00   Median : 45.00  
##  Mean   :2.72   Mean   :0.98   Mean   :12.17   Mean   : 45.52  
##  3rd Qu.:4.00   3rd Qu.:1.00   3rd Qu.:14.00   3rd Qu.: 63.00  
##  Max.   :5.00   Max.   :2.00   Max.   :18.00   Max.   :100.00  
##      salary      
##  Min.   :  3.00  
##  1st Qu.:  9.00  
##  Median : 15.00  
##  Mean   : 21.24  
##  3rd Qu.: 22.25  
##  Max.   :135.00</code></pre>
<pre class="r"><code>addmargins( table(jobdur$dur) )</code></pre>
<pre><code>## 
##   1   2   3   4   5 Sum 
##  29  21  20   9  21 100</code></pre>
</div>
<div id="data-handling-1" class="section level2">
<h2>Data Handling</h2>
<pre class="r"><code>jobdur$censored &lt;- jobdur$event != 1
addmargins(table(jobdur$censored))</code></pre>
<pre><code>## 
## FALSE  TRUE   Sum 
##    68    32   100</code></pre>
<pre class="r"><code>addmargins(table(jobdur$event))</code></pre>
<pre><code>## 
##   0   1   2 Sum 
##  17  68  15 100</code></pre>
<pre class="r"><code>Surv_time &lt;- with(jobdur , Surv(dur, censored))</code></pre>
</div>
<div id="survival-curves-life-table-1" class="section level2">
<h2>Survival curves &amp; Life Table</h2>
<ol style="list-style-type: decimal">
<li>Simple survival curve that doesn’t consider any different groupings</li>
</ol>
<pre class="r"><code>fit &lt;- survfit(Surv_time~1, data = jobdur)
fit</code></pre>
<pre><code>## Call: survfit(formula = Surv_time ~ 1, data = jobdur)
## 
##       n  events  median 0.95LCL 0.95UCL 
##     100      32       5       5       5</code></pre>
<pre class="r"><code>summary(fit)</code></pre>
<pre><code>## Call: survfit(formula = Surv_time ~ 1, data = jobdur)
## 
##  time n.risk n.event survival std.err lower 95% CI upper 95% CI
##     1    100       7    0.930  0.0255       0.8813        0.981
##     2     71       3    0.891  0.0330       0.8283        0.958
##     3     50       4    0.819  0.0457       0.7346        0.914
##     4     30       1    0.792  0.0517       0.6970        0.900
##     5     21      17    0.151  0.0686       0.0619        0.368</code></pre>
<pre class="r"><code>plot(fit)</code></pre>
<p><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-38-1.png" width="672" /></p>
<p>Or using the package <code>survminer</code> and <code>ggsurvplot()</code> function:</p>
<pre class="r"><code>library(survminer)
ggsurvplot(fit)</code></pre>
<p><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-39-1.png" width="672" /></p>
<ol start="2" style="list-style-type: decimal">
<li>Curves depending on education level.</li>
</ol>
<p>Let use the factor depending on education level <span class="math inline">\(&gt;12\)</span></p>
<pre class="r"><code>ed_level &lt;- factor(jobdur$ed&gt;12, labels=c(&#39;Low Educ&#39;, &#39;High Educ&#39;) )</code></pre>
<pre class="r"><code>sfit &lt;- survfit(Surv_time~ed_level, data = jobdur)
sfit</code></pre>
<pre><code>## Call: survfit(formula = Surv_time ~ ed_level, data = jobdur)
## 
##                     n events median 0.95LCL 0.95UCL
## ed_level=Low Educ  55     13      5       5      NA
## ed_level=High Educ 45     19      5       5       5</code></pre>
<pre class="r"><code>summary(sfit)</code></pre>
<pre><code>## Call: survfit(formula = Surv_time ~ ed_level, data = jobdur)
## 
##                 ed_level=Low Educ 
##  time n.risk n.event survival std.err lower 95% CI upper 95% CI
##     1     55       3    0.945  0.0306       0.8873        1.000
##     2     36       3    0.867  0.0518       0.7708        0.974
##     3     23       2    0.791  0.0695       0.6662        0.940
##     5      6       5    0.132  0.1209       0.0219        0.796
## 
##                 ed_level=High Educ 
##  time n.risk n.event survival std.err lower 95% CI upper 95% CI
##     1     45       4    0.911  0.0424       0.8316        0.998
##     3     27       2    0.844  0.0604       0.7331        0.971
##     4     20       1    0.801  0.0706       0.6743        0.953
##     5     15      12    0.160  0.0840       0.0574        0.448</code></pre>
<pre class="r"><code>plot(sfit)
ggsurvplot(sfit, conf.int=TRUE, pval=TRUE, risk.table=TRUE, 
           legend.labs=c(&quot;Low Educ&quot;, &quot;High Educ&quot;), legend.title=&quot;Sex&quot;,  
           palette=c(&quot;dodgerblue2&quot;, &quot;orchid2&quot;), 
           title=&quot;KM Curve for Jub Duration Survival&quot;, 
           risk.table.height=.15)</code></pre>
<pre><code>## Warning: Vectorized input to `element_text()` is not officially supported.
## Results may be unexpected or may change in future versions of ggplot2.</code></pre>
<p><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-41-1.png" width="672" /><img src="/lessons_list/lesson_3-2_SurvAnalyse-APPLICATION_files/figure-html/unnamed-chunk-41-2.png" width="672" /></p>
</div>
<div id="exercise-inspired-from-chapter-7-of-vinods--on-intermediate-econometrics-using-r" class="section level2">
<h2>Exercise inspired from “Chapter 7 of Vinod’s -ON INTERMEDIATE ECONOMETRICS USING R”</h2>
<!--
Download \strikeDuration.txt" data le from my website:
http://www.fordham.edu/economics/vinod/strikeDuration.txt It has
two variables \T" for durations of industrial labor strikes and unanticipated
production \Prod" which is a residual from a regression of log of industrial
production on time, time squared, and a set of monthly dummy variables.
It measures aggregate industrial production less trend and seasonal compo-
nents. Show the survival curves for these data. [Hint: Use snippet plotting
Figure 7.3 of the textbook] Since these data have only two variables, note
that we cannot plot a gure similar to the Figure 7.4 of the textbook. Use
a random seed of 356 and the `sample(1:62)' command to create a regional
dummy variable by splitting numbers below 31. Use `region' data and plot
similar to Figure 7.4 of the textbook. Since there was no censoring, censor
variable is a vector of all zeros. This choice however leads to non-convergence.
If we pretend that all data are censored, there is convergence with similar
coecients.
#Hints for artificial creation of the region dummy variable:
da=read.table("c:/data/strikeduration.txt", header=T)
33
summary(da)
n=length(da$T);n; censor=rep(0,n) #$
set.seed(356)
sa=sample(1:n)
region=ifelse( sa<(n/2), 0,1)
da2=cbind(da, censor, region);summary(da2)
library(survival); attach(da2)
survreg(Surv(T,censor)~Prod)
fit=coxph(Surv(T, rep(1,n)) ~ Prod)
plot(survfit(fit))
fit2=coxph(Surv(T, rep(1,n)) ~ Prod+strata(region))
plot(survfit(fit2)) #2 lines for 2 strata over and above Prod
library(Design) #new package called
fitD=survfit(Surv(T, rep(1,n)) ~ region)
survplot(fitD) #two lines for two strata alone (no Prod here)
Note that our articially created regions are not statistically signicantly
dierent from each other since the condence intervals for two survival curves
overlap.
-->
<div id="refs" class="references">
<div id="ref-Allison2010">
<p>Allison, Paul D. 2010. <em>Survival Analysis Using Sas: A Practical Guide, Second Edition</em>. 2nd ed. SAS Publishing.</p>
</div>
<div id="ref-Bivand2013">
<p>Bivand, Roger S., Edzer J. Pebesma, and Virgilio. Gómez-Rubio. 2008. <em>Applied Spatial Data Analysis with R</em>. New York; London: Springer.</p>
</div>
<div id="ref-lovelace2019">
<p>Lovelace, R., J. Nowosad, and J. Muenchow. 2019. <em>Geocomputation with R</em>. Chapman &amp; Hall/Crc the R Series. CRC Press. <a href="https://books.google.fr/books?id=0y6ODwAAQBAJ">https://books.google.fr/books?id=0y6ODwAAQBAJ</a>.</p>
</div>
</div>
</div>
</div>

		</div>
		<footer class="post__footer">
			
<div class="post__tags tags clearfix">
	<svg class="tags__badge icon icon-tag" width="16" height="16" viewBox="0 0 32 32"><path d="M32 19c0 1-1 2-1 2L21 31s-1 1-2 1-2-1-2-1L2 16c-1-1-1.4-2-1.4-2S0 12.5 0 11V3C0 1.5.8.8.8.8S1.5 0 3 0h8c1.5 0 3 .6 3 .6S15 1 16 2l15 15s1 1 1 2zM7 10a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/></svg>
	<ul class="tags__list">
		<li class="tags__item">
			<a class="tags__link btn" href="/tags/r-markdown/" rel="tag">R Markdown</a>
		</li>
		<li class="tags__item">
			<a class="tags__link btn" href="/tags/plot/" rel="tag">plot</a>
		</li>
		<li class="tags__item">
			<a class="tags__link btn" href="/tags/regression/" rel="tag">regression</a>
		</li>
	</ul>
</div>
		</footer>
	</article>
</main>


<nav class="pager flex">
	<div class="pager__item pager__item--prev">
		<a class="pager__link" href="/lessons_list/lesson_3_survanalyse/" rel="prev">
			<span class="pager__subtitle">«&thinsp;Previous</span>
			<p class="pager__title">Introduction to Survival Analysis</p>
		</a>
	</div>
	<div class="pager__item pager__item--next">
		<a class="pager__link" href="/lessons_list/lesson_0.1_reproducibleresearch/" rel="next">
			<span class="pager__subtitle">Next&thinsp;»</span>
			<p class="pager__title">Introduction to Reproducible Analysis</p>
		</a>
	</div>
</nav>


			</div>
			
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2020 Smart Analytics for Big Data.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>
	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>