baseurl = "https://sabd-smartanalytics.netlify.app/"
title = "Smart Analytics for Big Data"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "Mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[Author]
  name = "Iragaël Joly"
  bio = "Iragaël Joly"
  avatar = "img/avatar.png"


[Params]
  description = "Smart Analytics for Big Data" # Description of your site
  opengraph = true
  twitter_cards = false
  readmore = false # Show "Read more" button in list if true
  authorbox = false
  pager = true
  post_meta = ["date", "categories"] # Order of post meta information

[Params.logo]
  subtitle = "Lesson at Grenoble Inp - IEM" # Logo subtitle



[[menu.main]]
    name = "Lessons"
    url = "/lessons-list/"
    weight = 3

    
[[menu.main]]
    name = "Recordings"
    url = "/Recordings/"
    weight = 4

[[menu.main]]
    name = "PreRequisites"
    url = "/PreRequisites/"
    weight = 5
    
[[menu.main]]
    name = "Other Lessons"
    url = "/OtherLessons/"
    weight = 6
  

[[menu.main]]
    name = "References"
    url = "/References/"
    weight = 7