---
title: "Smart Analytics for Big Data"
subtitle: "Lessons list"
author: "Iragaël Joly"
date: "Automn 2020"
categories: ["R"]
tags: ["R Markdown", "plot", "regression"]
authorbox: false
---

# Lessons list

This is the website of the Lesson **Smart Analytics for Big Data** taught at Grenoble INP Industrial Engineering and Management School & UGA.

## First Lesson - 01/10/2020 - 9:30 - 12:30

Welcome page of [First Lesson](../post/first-lesson-october-1rst-2020)

## Second Lesson - 08/10/2020 - 8:00 - 12:30

Material for the [Second Lesson](../post/Second-lesson-october-8th-2020)

## Third Lesson - 15/10/2020 - 9:30 - 12:30

Material for the [Third Lesson](../post/Third-lesson-october-15th-2020)

## Fourth Lesson - 22/10/2020 - 8:00 - 12:30

Material for the [Fourth Lesson](../post/2020-10-22-Fourth-lesson-october-22th-2020)


## Fifth Lesson - 05/11/2020 - 8:00 - 12:30

Material for the [Fifth Lesson](../post/Fifth-lesson-november-05th-2020)


## Sixth Lesson - 12/11/2020 - 9:30 - 12:30

Material for the [Sixth Lesson](../post/Sixth-lesson-november-12th-2020)

***

**to come...**

**Test**:

## Sixth Lesson - 12/11/2020 - 9:30 - 12:30

Material for the [Sixth Lesson V2](../post/Sixth-lesson-november-12th-2020_V2)

***

## Seventh Lesson - 19/11/2020 - 9:30 - 12:30 **and 13:30 - 15:00**

Material for the [Seventh Lesson](../post/Seventh-lesson-november-19th-2020)

## Eighth Lesson - 26/11/2020 - 13:30 - 18:00

Material for the [Eighth Lesson](../post/Eighth-lesson-november-26th-2020)

### Nineth Lesson - 03/12/2020 - **13:30 - 18:00**

### Tenth Lesson - 10/12/2020 - **13:30 - 18:00**

### Eleventh Lesson - 17/12/2020 - **08:00 - 12:30**

### Twelveth Lesson - 17/12/2020 - **08:00 - 12:30**
