## RMarkdown  and Dynamic document

Analyses need to be communicated to others. Publishing papers, blog posts, PowerPoint presentations, books or dashboards are many outputs or documents taht will be connected to the results analysis. 

R Markdown permits to publish documents integrated the analysis and visualization.

R Markdown is a package, as well as an ecosystem of tools. 

It allows to add R code to a plain-text file with some Markdown formatting.

Many output formats are rendered PDF, HTML, Microsoft Word, and Microsoft PowerPoint.

The rendering operation, also called knitting, runs the R code insert the resulting output and figures in the final document: a **dynamic document**.

Yihui Xie, J. J. Allaire, and Garrett Grolemund have written R Markdown: *The Definitive Guide* and also made the source R Markdown available on [GitHub](https://github.com/rstudio/rmarkdown-book) [^1].

[^1]: Note that many bookdowns are freely available online. (https://bookdown.org/)

Specialized packages extend R Markdown for blogging (`blogdown`), for books (`bookdown`), and for making gridded dashboards (`flexdashboard`). 

The initial package in the ecosystem is called `knitr`, and we still call the process of turning R Markdown into a final format knitting the document. 

Many output formats are supported by the R Markdown ecosystem, among which: HTML, LaTeX-pdf, Microsoft Word, and Microsoft PowerPoint.

R Markdown is not dependent on RStudio.
It’s possible to edit plain-text R Markdown files with a text editor and then knit the document using R’s command-line interface. 

However, the RStudio tools are so helpful.



