---
title: "Regression Modelling: Categorical Outcome"
subtitle: "Seventh Lesson November 19th 2020"
author: IJ
date: '2020-11-19'
slug: seventh-lesson
categories:
  - Lesson
tags:
  - Lesson
description: ''
thumbnail: ''
---

The 7th lesson is divided in

- [Regression Modeling: Categorical Outcome]{#Regression}
- [Project: Mobility analysis]{#Project}


# Regression Modelling: Categorical Outcome {#Regression}


Welcome to the Seventh lesson - 19/11/2020 9:30 - 12:30 **and 13:30 - 15:00**

Teacher: I Joly 

## Zoom meeting

**From 09:30 to 12:30**

1. following this link: (https://grenoble-inp.zoom.us/j/93438334161?pwd=dC9EemxIWmJlY3dqa2d3OWZpcHZ2QT09)

(and, if needed, install the zoom app).

1. or you can start the Zoom app with the following information
  + meeting ID: 934 3833 4161
  + Password: SABD2020


## Material

- **Lesson Material**[Slides](/Data-pdf/SABD_Project_2020_V2.pdf)
- files used in the lesson 
  + [tab151.txt](/Data-pdf/logistic/Tab151.txt)
  + [oddsratio.R](/Data-pdf/logistic/oddsratio.R)
- Exercise: **Death Penalty**
  + **Statement** in Rmd format: [lesson_7.2_Allison_Penalty_STATEMENT_SABD.Rmd](/Data-pdf/lesson_7.2_Allison_Penalty_STATEMENT_SABD.Rmd)
  + **Data**: [02_Penalty.txt](/Data-pdf/logistic/02_Penalty.txt)

***

# Project: Mobility analysis {#Project}

**From 13:30 to 15:00**

1. following this link: (https://grenoble-inp.zoom.us/j/98780829655?pwd=VDdod2xJODMvQ3cxWnA4M1FxTFFqdz09)

(and, if needed, install the zoom app).

1. or you can start the Zoom app with the following information
  + meeting ID: 987 8082 9655
  + Password: SABD2020



## Project page:

All documents, data, etc are on [Caseine](https://moodle.caseine.org/course/view.php?id=644&sectionid=5661)

You will upload your report (`.Rmd` and `.pdf` on [Caseine also](https://moodle.caseine.org/mod/groupselect/view.php?id=32895))






